define({
    "ERR_LOADING" : "Carga Fallida :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Abrir Administrador de Conexiones",
    "SIDEPANEL_FILETREE_NAME" : "Nombre",
    "SIDEPANEL_FILETREE_SIZE" : "Tamaño",
    "SIDEPANEL_FILETREE_TYPE" : "Tipo",
    "SIDEPANEL_FILETREE_MODIFIED" : "Modificado",
    "SIDEPANEL_CONDISCONNECT" : "(Des)conectar",
    "SIDEPANEL_REFRESH" : "Refrescar",
    "SIDEPANEL_RELOADSETTINGS" : "Recargar configuración y reingresar la contraseña",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "El servidor no existe",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Parece que el servidor no existe.<br>Revise el apartado de Servidor en la configuración de conexión.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "No se puede conectar al servidor",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "No puedo conectar al servidor.<br>Tal vez tu Firewall no me deja hacerlo.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Datos de autenticación incorrectos",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "No puedo autenticar con los datos que me diste.<br>Por favor revísalos.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "No se puede encontrar la conexión",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "No hay ningún servidor conectado ni conexiones eqFTP asociadas al proyecto actual.<br>Conéctese a un servidor o especifique la carpeta del proyecto actual como directorio local para conexión en la configuración.",
    "ERR_DIAG_ECONNRESET_TITLE" : "Servidor esta rechazando conexiones",
    "ERR_DIAG_ECONNRESET_CONTENT" : "No me puedo conectar al servidor, el no me lo permite.<br>Prueba reiniciando Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Ha sido desconectado del servidor",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Conexión abortada. Intente reconectarse.",
    "ERR_DIAG_UNIVERSAL_TITLE" : "Aquí hay un error",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Mira este error! Como pudo pasar esto?",
    "ERR_DIAG_NORSAKEYFOUND" : "No se encontró la clave RSA en: ",

    "NOT_DIAG_CONNECTED" : "Conectado al servidor.",
    "NOT_DIAG_DISCONNECTED" : "Desconectado del servidor",
    "NOT_DIAG_FILESDIFFERENT" : "Hay diferencias entre los archivos remotos y locales. Clickee aqui para más acciones.",

    "PASSWDWIND_TITLE" : "Por favor ingrese su contraseña",
    "PASSWDWIND_CONTENT" : "Su contraseña para eqFTP:",

    "CHECKDIFF_TITLE" : "Hay diferencias entre los archivos",
    "CHECKDIFF_CONTENT" : "El archivo remoto es diferente al local. Elija la acción que quiera seguir.",
    "CHECKDIFF_BUTTON_COMPARE" : "Comparar archivos",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Mostrar cambios",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Conservar archivo local",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Conservar archivo local para la cola actual",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Obtener archivo remoto",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Obtener archivo remoto para la cola actual",

    "SETTINGSWIND_TITLE" : "Administrador de conexiones eqFTP",
    "SETTINGSWIND_ERR_BLANKS" : "Oops! Parece que algo salio mal. Revisa los datos y prueba nuevamente.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Algo salio completamente mal! No puedo escribir la configuración en el archivo!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "El directorio que estas intentando ingresar esta siendo utilizado por otra conexión.",
    "SETTINGSWIND_NOTIF_DONE" : "Todo se guardo! :)",
    "SETTINGSWIND_SAVEDCONN" : "Conexiones FTP guardas",
    "SETTINGSWIND_DELETECONN_HOVER" : "Borrar esta conexión",
    "SETTINGSWIND_COPYCONN_HOVER" : "Copiar esta conexión",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "Usted no puede borrar la conexión que está usando en este momento.",
    "SETTINGSWIND_ADDCONN_HOVER" : "Agregar nueva conexión",
    "SETTINGSWIND_ADDCONN_STRING" : "Crear nueva conexión...",
    "SETTINGSWIND_DELETECONNCONF_1" : "Por favor confirme el borrado de la conexión ", // Those 2 strings are going like this: SETTINGSWIND_DELETECONNCONF_1 + VAL + SETTINGSWIND_DELETECONNCONF_2
    "SETTINGSWIND_DELETECONNCONF_2" : ".", // So if in your language there's no need in 2 strings, just leave one of them blank
    "SETTINGSWIND_OPENGLOBSET" : "Abrir configuración global de FTP...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Seleccione la conexión a editar en el panel lateral o cree una nueva.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Carpeta para proyectos:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Carpeta para proyectos con archivos descargados:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Carpeta para configuración:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Carpeta para el archivo de configuración",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "No abra los proyectos después de la descarga",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "Contraseña maestra",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Nombre de conexión:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Digite el nombre de la conexión",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Servidor:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Tipo de protocolo:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Nombre de usuario:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "Usuario FTP",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Contraseña:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "Contraseña FTP",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "Clave RSA",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "De clic para seleccionar una clave RSA",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Elija la ruta a su clave RSA",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Directorio remoto:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Digite el directorio remoto de la carpeta raíz del proyecto",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Directorio local:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Si no se define crea una nueva carpeta en el directorio por defecto",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Subir archivo al guardar",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Poner la cola en pausa.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Aún si esta desconectado",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Esta opción automáticamente se conecta al servidor cuando un archivo guardado es abierto del servidor o el archivo y el proyecto fueron creados por esta extensión.",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Inserte la ubicación del proyecto actual",
    "SETTINGSWIND_GLOB_FRM_TITLE" : "Escoger método de obtención de carpetas:",
    "SETTINGSWIND_GLOB_FRM_LIST" : "Usar comando LIST",
    "SETTINGSWIND_GLOB_FRM_MLSD" : "Usar comando MLSD",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Intervalo de comandos para mantener activo:", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Valor en segundos. Valor recomendado 10. Use cero para prohibir  los comandos para mantener activo y desconectar del servidor  cada vez que el comando es ejecutado.",
    "SETTINGSWIND_GLOB_DEBUG" : "Depurar:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Formato de fecha:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Europeo",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Asiático",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "Autolimpieza de la cola",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notificaciones",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Compensación de tiempo:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Use esta opción para ver correctamente el tiempo en la columna Modificaciones",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Conexión",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatización",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Advanzado",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Ajustar automatización:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Sincronizar",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Clásico",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Elija que sincronizar",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "Crear archivos",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Crear carpetas",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "Actualizar Archivos",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Renombrar",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Mover",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Borrar",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Configuraciones adicionales",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Verificar las diferencias",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "Cuando usted abre un archivo local o remoto",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Ignorar lista",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "La misma sintáxis que en .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Conmutación: Abrir el proyecto local después de realizada la conexión y viceversa",
    "SETTINGS_NOTIF_RELOADED" : "La configuración se a recargado satisfactoriamente..",
    "SETTINGS_ERROR_RELOADED" : "No se ha podido recargar la configuración.",
    "SETTINGSWIND_GLOB_SCE_TITLE" : "Usar comandos SSH con SFTP",

    "QUEUE_TITLE" : "Cola de eqFTP",
    "QUEUE_HEADER_NAME" : "Nombre",
    "QUEUE_HEADER_PATH" : "Directorio",
    "QUEUE_HEADER_FROM" : "Directorio de fuente",
    "QUEUE_HEADER_TO" : "Directorio destino",
    "QUEUE_HEADER_STATUS" : "Estado",
    "QUEUE_CLEARQ" : "Limpiar cola",
    "QUEUE_STARTQ" : "Iniciar la cola",
    "QUEUE_PAUSEQ" : "Pausar la cola",
    "QUEUE_RESTARTQ" : "Falló la reiniciación",
    "QUEUE_CONTEXTM_STARTT" : "Iniciar",
    "QUEUE_CONTEXTM_PAUSET" : "Pausar",
    "QUEUE_CONTEXTM_REMOVET" : "Remover",
    "QUEUE_CONTEXTM_RESTARTT" : "Reiniciar",
    "QUEUE_TASK_STATUS_WAITING" : "Esperando",
    "QUEUE_TASK_STATUS_SUCCESS" : "Hecho",
    "QUEUE_TASK_STATUS_FAIL" : "Falló",
    "QUEUE_TASK_STATUS_PAUSE" : "Pausado",
    "QUEUE_TASK_STATUS_STARTED" : "Iniciado",
    "QUEUE_TASK_STATUS_DELETED" : "Borrado",
    "QUEUE_DONT_ADD_COMPLETED" : "Autolimpieza. Tareas completas",
    
    "ERR_FILE_ACCESSDENIED" : "Acceso denegado. Revise los permisos del archivo.",
    "ERR_FILE_AUTHORIZATION" : "Error de autenticación. Revise su usuario y contraseña.",
    "ERR_FILE_SERVNOEXIST" : "El servidor no existe. Tal vez tu lo escribiste mal.",
    "ERR_FILE_SERVCANTREACH" : "No se puede conectar al servidor. Revise el Firewall.",
    "ERR_FILE_FILESIZE0" : "No se puede descargar el archivo (Tamaño es 0)",
    "ERR_FILE_DOWNLOAD" : "No se puede descargar el archivo.",
    "ERR_FILE_UPLOAD" : "No se puede cargar el archivo.",
    "ERR_FILE_DOESNTEXIST" : "El archivo no existe",
    "ERR_FILE_CANTRENAME" : "No se puede renombrar el archivo: ",
    "ERR_FILE_CANTDELETE" : "No se puede borrar el archivo: ",
    "ERR_FILE_CANTCREATEDIR" : "No se puede crear la carpeta: ",
    "ERR_FILE_CANTDELETEDIR" : "No se puede borrar la carpeta: ",
    "ERR_FILE_CANTCREATEFILE" : "No se puede crear el archivo: ",
    "ERR_FOLDER_OPEN" : "Hay un error al abrir la carpeta como proyecto.",

    "CONTEXTM_DOWNLOAD" : "Descargar",
    "CONTEXTM_UPLOAD" : "Subir",
    "CONTEXTM_ADDQUEUE" : "Añadir a la cola",
    "CONTEXTM_OPEN" : "Abrir",
    "CONTEXTM_DELETE" : "Borrar",
    "CONTEXTM_RENAME" : "Renombrar",
    "CONTEXTM_REDOWNLOAD" : "Descargar del servidor",
    "CONTEXTM_CREATEFILE" : "Crear archivo",
    "CONTEXTM_CREATEFOLDER" : "Crear carpeta",

    "OTHER_SELECT_SERVER_DROPDOWN" : "Seleccione el servidor remoto a conectar...",
    "OTHER_ERROR" : "Error",
    "OTHER_PAUSED" : "Pausado",
    "OTHER_COMPLETED" : "Completado",
    "OTHER_CANCELLED" : "Cancelado",
    "OTHER_WAITING" : "Esperando",
    "OTHER_YES" : "Si",
    "OTHER_NO" : "No",
    "OTHER_OK" : "Aceptar",
    "OTHER_OFF" : "Detener",
    "OTHER_CANCEL" : "Cancelar",
    "OTHER_APPLY" : "Aplicar",
    "OTHER_SAVE" : "Guardar",
    "OTHER_CLOSE" : "Cerrar",
    "OTHER_DELETE" : "Borrar",
    "OTHER_CONFIRM_DELETE" : "Esta seguro que desea borrar este ítem?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "Hay algunos cambios que no se han guardado, estos se perderan si hace clic en ACEPTAR.<br>¿Qué quiere hacer?",
    "OTHER_ERROR_EVENDISCONN" : "No se puede cargar el archivo. La opción 'Aún si está desconectado' no está seleccionada.",
    "OTHER_ERROR_CANTREADSETTINGS" : "No se ha podido leer su archivo de configuración, es posible que haya digitado mal su contraseña"
});