define({
    "ERR_LOADING" : "Carga fallida :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Abrir administrador de conexiones",
    "SIDEPANEL_FILETREE_NAME" : "Nombre",
    "SIDEPANEL_FILETREE_SIZE" : "Tamaño",
    "SIDEPANEL_FILETREE_TYPE" : "Tipo",
    "SIDEPANEL_FILETREE_MODIFIED" : "Modificado",
    "SIDEPANEL_CONDISCONNECT" : "(Des)conectar",
    "SIDEPANEL_REFRESH" : "Refrescar",
    "SIDEPANEL_RELOADSETTINGS" : "Recargar configuración y reingresar la contraseña",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "El servidor no existe",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Parece que el servidor no existe.<br>Revise el apartado Servidor en las opciones de conexión.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "No se puede conectar al servidor",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "No puedo conectar al servidor.<br>Tal vez tu Firewall no me deja hacerlo.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Datos de autenticación incorrectos",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "No puedo autenticar con los datos que me diste.<br>Por favor revísalos.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "No se puede encontrar la conexión",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "No hay ningún servidor conectado ni conexiones eqFTP asociadas al proyecto actual.<br>Conéctese a un servidor o especifique la carpeta del proyecto actual como directorio local para conexión en la configuración.",
    "ERR_DIAG_ECONNRESET_TITLE" : "El servidor está rechazando conexiones",
    "ERR_DIAG_ECONNRESET_CONTENT" : "No me puedo conectar al servidor, no me lo permite.<br>Prueba a reiniciar Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Ha sido desconectado del servidor",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Conexión abortada. Tratando de reconectar...",
    "ERR_DIAG_UNIVERSAL_TITLE" : "Hay un error",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "¡Mira este error! ¿Cómo pudo pasar esto?",

    "NOT_DIAG_CONNECTED" : "Conectado al servidor.",
    "NOT_DIAG_DISCONNECTED" : "Desconectado del servidor.",
    "NOT_DIAG_FILESDIFFERENT" : "Hay diferencias entre los archivos locales y los remotos. Haz clic aquí para ver más acciones.",

    "PASSWDWIND_TITLE" : "Por favor ingrese su contraseña",
    "PASSWDWIND_CONTENT" : "Su contraseña para eqFTP:",

    "CHECKDIFF_TITLE" : "Hay diferencias entre ficheros",
    "CHECKDIFF_CONTENT" : "Las copias remotas y locales del archivo son diferentes. Por favor, seleccione la acción que desea realizar.",
    "CHECKDIFF_BUTTON_COMPARE" : "Comparar archivos",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Mostrar cambios",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Mantener el local",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Mantener las copias locales para la cola actual",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Obtener el remoto",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Obtener las copias remotas para la cola actual",

    "SETTINGSWIND_TITLE" : "Administrador de conexiones eqFTP",
    "SETTINGSWIND_ERR_BLANKS" : "¡Oops! Parece que algo salió mal. Revise los datos y pruebe de nuevo.",
    "SETTINGSWIND_ERR_CANTWRITE" : "¡Algo salió completamente mal! ¡No puedo escribir la configuración en el archivo!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "El directorio que está intentando insertar esta siendo utilizado por otra conexión.",
    "SETTINGSWIND_NOTIF_DONE" : "¡Todo se ha guardado! :)",
    "SETTINGSWIND_SAVEDCONN" : "Conexiones FTP guardadas",
    "SETTINGSWIND_DELETECONN_HOVER" : "Borrar esta conexión",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "No puede borrar la conexión que estás usando actualmente",
    "SETTINGSWIND_ADDCONN_HOVER" : "Agregar nueva conexión",
    "SETTINGSWIND_ADDCONN_STRING" : "Crear nueva conexión...",
    "SETTINGSWIND_DELETECONNCONF_1" : "Por favor, confirme el borrado de la conexión ", // Those 2 strings are going like this: SETTINGSWIND_DELETECONNCONF_1 + VAL + SETTINGSWIND_DELETECONNCONF_2
    "SETTINGSWIND_DELETECONNCONF_2" : " .", // So if in your language there's no need in 2 strings, just leave one of them blank
    "SETTINGSWIND_OPENGLOBSET" : "Abrir configuración global de FTP...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Seleccione la conexión a editar en el panel lateral o cree una nueva.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Carpeta para proyectos:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Carpeta para proyectos con archivos descargados:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Carpeta para configuración:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Carpeta para el archivo de configuración",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "No abra los proyectos después de la descarga",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "Contraseña maestra",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Nombre de la conexión:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Escriba el nombre de la conexión",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Servidor:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Tipo de protocolo:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Nombre de usuario:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "Usuario FTP",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Contraseña:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "Contraseña FTP",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "Clave RSA",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "Clic para seleccionar la clave RSA",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Escoja una ruta para la clave RSA",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Directorio remoto:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Escriba la ruta remota de la carpeta raíz del proyecto",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Directorio local:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Crea una nueva carpeta en la ruta por defecto si no se define",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Subir archivo al guardar",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Añadir a la cola pausada.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Aún si está desconectado",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Esta opción automáticamente se conecta al servidor cuando un archivo guardado es abierto desde el servidor o un archivo guardado se encuentra en el proyecto actual y este mismo proyecto fue creado por esta extensión FTP. Espero haberme explicado bien...",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Inserte la ubicación del proyecto actual",
    "SETTINGSWIND_GLOB_USELIST" : "Obtención de carpeta alternativa",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Intervalo para mantener activa la conexión:", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Valor en segundos. El valor recomendado es 10. Use cero para no mantener activa la conexión y desconectar del servidor cada vez que un comando se complete.",
    "SETTINGSWIND_GLOB_DEBUG" : "Depurar:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Formato de fecha:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Europeo",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Asiático",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "Auto-limpiar la cola",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notificaciones",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Compensación de tiempo:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Use esta opción para establecer el tiempo correcto en la columna Modificado",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Conexión",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatización",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Avanzado",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Establecer automatización:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Sincronizar",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Clásico",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Seleccione que quiere sincronizar",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "Creación de archivo",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Creación de carpeta",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "Actualización de archivo",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Renombrando",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Moviendo",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Borrando",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Más opciones",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Comprobar diferencias",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "Cuando abre el archivo local o remoto",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Ignorar lista",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Misma sintaxis que en .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Abre el proyecto local relacionado después de cambiar la conexión y viceversa",
    "SETTINGS_NOTIF_RELOADED" : "La configuración se ha recargado correctamente.",
    "SETTINGS_ERROR_RELOADED" : "No se puede recargar la configuración.",

    "QUEUE_TITLE" : "Cola de eqFTP",
    "QUEUE_HEADER_NAME" : "Nombre",
    "QUEUE_HEADER_PATH" : "Directorio",
    "QUEUE_HEADER_FROM" : "Directorio fuente",
    "QUEUE_HEADER_TO" : "Directorio destino",
    "QUEUE_HEADER_STATUS" : "Estado",
    "QUEUE_CLEARQ" : "Limpiar cola",
    "QUEUE_STARTQ" : "Iniciar cola",
    "QUEUE_PAUSEQ" : "Pausar cola",
    "QUEUE_RESTARTQ" : "Fallo al reiniciar",
    "QUEUE_CONTEXTM_STARTT" : "Iniciar",
    "QUEUE_CONTEXTM_PAUSET" : "Pausar",
    "QUEUE_CONTEXTM_REMOVET" : "Borrar",
    "QUEUE_CONTEXTM_RESTARTT" : "Reiniciar",
    "QUEUE_TASK_STATUS_WAITING" : "Esperar",
    "QUEUE_TASK_STATUS_SUCCESS" : "Hecho",
    "QUEUE_TASK_STATUS_FAIL" : "Fallado",
    "QUEUE_TASK_STATUS_PAUSE" : "Pausado",
    "QUEUE_TASK_STATUS_STARTED" : "Iniciado",
    "QUEUE_TASK_STATUS_DELETED" : "Borrado",
    "QUEUE_DONT_ADD_COMPLETED" : "Auto-limpiar las tareas completadas",
    
    "ERR_FILE_ACCESSDENIED" : "Acceso denegado. Revise los permisos del archivo.",
    "ERR_FILE_AUTHORIZATION" : "Error de autenticación. Revise su usuario y contraseña.",
    "ERR_FILE_SERVNOEXIST" : "El servidor no existe. Tal vez lo escribió mal.",
    "ERR_FILE_SERVCANTREACH" : "No se puede conectar al servidor. Revise su Firewall.",
    "ERR_FILE_FILESIZE0" : "No se puede descargar el archivo. Su tamaño es 0.",
    "ERR_FILE_DOWNLOAD" : "No se puede descargar el archivo.",
    "ERR_FILE_UPLOAD" : "No se puede subir el archivo.",
    "ERR_FILE_DOESNTEXIST" : "El archivo no existe",
    "ERR_FILE_CANTRENAME" : "No se puede renombrar el archivo: ",
    "ERR_FILE_CANTDELETE" : "No se puede borrar el archivo: ",
    "ERR_FILE_CANTCREATEDIR" : "No se puede crear la carpeta: ",
    "ERR_FILE_CANTDELETEDIR" : "No se puede borrar la carpeta: ",
    "ERR_FILE_CANTCREATEFILE" : "No se puede crear el archivo: ",
    "ERR_FOLDER_OPEN" : "Ha ocurrido un error al abrir la carpeta como proyecto",

    "CONTEXTM_DOWNLOAD" : "Descargar",
    "CONTEXTM_UPLOAD" : "Subir",
    "CONTEXTM_ADDQUEUE" : "Añadir a la cola",
    "CONTEXTM_OPEN" : "Abrir",
    "CONTEXTM_DELETE" : "Borrar",
    "CONTEXTM_RENAME" : "Renombrar",
    "CONTEXTM_REDOWNLOAD" : "Descargar desde el servidor",
    "CONTEXTM_CREATEFILE" : "Crear archivo",
    "CONTEXTM_CREATEFOLDER" : "Crear carpeta",

    "OTHER_SELECT_SERVER_DROPDOWN" : "Seleccione el servidor remoto a conectar...",
    "OTHER_ERROR" : "Error",
    "OTHER_PAUSED" : "Pausado",
    "OTHER_COMPLETED" : "Completado",
    "OTHER_CANCELLED" : "Cancelado",
    "OTHER_WAITING" : "Esperando",
    "OTHER_OK" : "Aceptar",
    "OTHER_OFF" : "Apagar", //¿Puede referirse a apagado?
    "OTHER_CANCEL" : "Cancelar",
    "OTHER_APPLY" : "Aplicar",
    "OTHER_SAVE" : "Guardar",
    "OTHER_CLOSE" : "Cerrar",
    "OTHER_DELETE" : "Borrar",
    "OTHER_CONFIRM_DELETE" : "¿Está seguro de que desea borrar este elemento?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "Hay algunos cambios no guardados que se perderán si pulsa en Aceptar.<br>¿Desea proceder?",
    "OTHER_ERROR_EVENDISCONN" : "No se puede subir el archivo. La opción 'Aún si está desconectado' no está activada.",
    "OTHER_ERROR_CANTREADSETTINGS" : "No se puede leer el archivo de configuración. Probablemente haya escrito mal la contraseña maestra."
});
