define({
    "ERR_LOADING" : "Loading failed :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Open Connection Manager",
    "SIDEPANEL_FILETREE_NAME" : "Name",
    "SIDEPANEL_FILETREE_SIZE" : "Size",
    "SIDEPANEL_FILETREE_TYPE" : "Type",
    "SIDEPANEL_FILETREE_MODIFIED" : "Modified",
    "SIDEPANEL_CONDISCONNECT" : "(Dis)connect",
    "SIDEPANEL_REFRESH" : "Refresh",
    "SIDEPANEL_RELOADSETTINGS" : "Reload Settings & Re-enter Password",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "Server Doesn't Exist",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Looks like this server doesn't exist.<br>Check Server filed in connection settings.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "Can't Reach Server",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "I just can't reach server.<br>Maybe your Firewall don't let me do this.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Incorrect Authorization Data",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "I can't authorize with those login and password you gave me.<br>Please check them.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "Can't find connection",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "There are no eqFTP connections tied with current project and no connected server.<br>Connect to server or specify current project's folder as local path for connection in Settings.",
    "ERR_DIAG_ECONNRESET_TITLE" : "Server denying connections",
    "ERR_DIAG_ECONNRESET_CONTENT" : "I can't connect to server, it doesn't allows me.<br>Try restart Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "You've been disconnected from server",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Connection aborted. Trying to reconnect...",
    "ERR_DIAG_UNIVERSAL_TITLE" : "There's an error",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Look at this error! How could it happen?",
    "ERR_DIAG_NORSAKEYFOUND" : "There's no RSA key found in: ",

    "NOT_DIAG_CONNECTED" : "Connected to server.",
    "NOT_DIAG_DISCONNECTED" : "Disconnected from server.",
    "NOT_DIAG_FILESDIFFERENT" : "There's a difference between local and remote files. Click here for more actions.",

    "PASSWDWIND_TITLE" : "Please Enter Your Password",
    "PASSWDWIND_CONTENT" : "Your Password for eqFTP:",

    "CHECKDIFF_TITLE" : "There's difference between files",
    "CHECKDIFF_CONTENT" : "Remote and local copies of file are different. Please choose an action you would like to do.",
    "CHECKDIFF_BUTTON_COMPARE" : "Compare files",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Show changes",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Keep local",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Keep local copies for current queue",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Get remote",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Get remote copies for current queue",

    "SETTINGSWIND_TITLE" : "eqFTP Connections Manager",
    "SETTINGSWIND_ERR_BLANKS" : "Oops! Looks like something is wrong. Check input fields and try again.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Something went totally wrong! I can't write settings to file!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "The path you're trying to insert is currently in use by another connection.",
    "SETTINGSWIND_NOTIF_DONE" : "Everything's saved! :)",
    "SETTINGSWIND_SAVEDCONN" : "Saved FTP Connections",
    "SETTINGSWIND_DELETECONN_HOVER" : "Delete This Connection",
    "SETTINGSWIND_COPYCONN_HOVER" : "Copy This Connection",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "You can't delete connection you're using now",
    "SETTINGSWIND_ADDCONN_HOVER" : "Add New Connection",
    "SETTINGSWIND_ADDCONN_STRING" : "Create New Connection...",
    "SETTINGSWIND_DELETECONNCONF_1" : "Please confirm deletion of ", // Those 2 strings are going like this: SETTINGSWIND_DELETECONNCONF_1 + VAL + SETTINGSWIND_DELETECONNCONF_2
    "SETTINGSWIND_DELETECONNCONF_2" : " connection.", // So if in your language there's no need in 2 strings, just leave one of them blank
    "SETTINGSWIND_OPENGLOBSET" : "Open Global FTP Settings...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Choose connection in sidebar for editing or create new.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Folder For Projects:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Directory for Projects with Downloaded Files:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Folder For Settings:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Directory for Settings File",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Don't Open Projects after Download",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "Master Password",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Connection Name:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Type in name of connection",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Server:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Protocol Type:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Username:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "FTP username",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Password:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "FTP password",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "RSA key",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "Click to select RSA key",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Choose path to RSA key",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Remote Path:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Type in the remote path to the project root folder",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Local Path:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Creates new folder in default location if blank",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Upload File on Save",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Add to paused queue.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Even If Disconnected",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "This option automatically connects to a server when a saved file is opened from the server or a saved file is within the current project and this project was created by this ftp extension. Oh, I really hope I explained it well...",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Insert current project's path",
    "SETTINGSWIND_GLOB_FRM_TITLE" : "Choose folder retrieving method:",
    "SETTINGSWIND_GLOB_FRM_LIST" : "Use LIST command",
    "SETTINGSWIND_GLOB_FRM_MLSD" : "Use MLSD command",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Keep alive interval:", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Value in seconds. Recommended value is 10. Use zero to forbid keep alive commands and disconnect from server every time command is done.",
    "SETTINGSWIND_GLOB_DEBUG" : "Debug:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Date Format:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "European",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Asian",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "Auto-clear Queue",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notifications",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Time Offset:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Use this option to set correct time for Modified column",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Connection",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatization",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Advanced",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Set automatization:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Sync",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Classic",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Select what to sync",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "File creation",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Folder creation",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "File update",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Renaming",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Moving",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Deleting",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Extra settings",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Check for differences",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "When you open local or remote file",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Ignore list",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Same syntax as in .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Open related Local project after switching connection and vice versa",
    "SETTINGS_NOTIF_RELOADED" : "Settings were successfully reloaded.",
    "SETTINGS_ERROR_RELOADED" : "Can't reload settings.",
    "SETTINGSWIND_GLOB_SCE_TITLE" : "Use SSH commands with SFTP",

    "QUEUE_TITLE" : "eqFTP Queue",
    "QUEUE_HEADER_NAME" : "Name",
    "QUEUE_HEADER_PATH" : "Path",
    "QUEUE_HEADER_FROM" : "Source Path",
    "QUEUE_HEADER_TO" : "Destination Path",
    "QUEUE_HEADER_STATUS" : "Status",
    "QUEUE_CLEARQ" : "Clear Queue",
    "QUEUE_STARTQ" : "Start Queue",
    "QUEUE_PAUSEQ" : "Pause Queue",
    "QUEUE_RESTARTQ" : "Restart Failed",
    "QUEUE_CONTEXTM_STARTT" : "Start",
    "QUEUE_CONTEXTM_PAUSET" : "Pause",
    "QUEUE_CONTEXTM_REMOVET" : "Remove",
    "QUEUE_CONTEXTM_RESTARTT" : "Restart",
    "QUEUE_TASK_STATUS_WAITING" : "Waiting",
    "QUEUE_TASK_STATUS_SUCCESS" : "Done",
    "QUEUE_TASK_STATUS_FAIL" : "Failed",
    "QUEUE_TASK_STATUS_PAUSE" : "Paused",
    "QUEUE_TASK_STATUS_STARTED" : "Started",
    "QUEUE_TASK_STATUS_DELETED" : "Deleted",
    "QUEUE_DONT_ADD_COMPLETED" : "Auto-clear Completed tasks",
    
    "ERR_FILE_ACCESSDENIED" : "Access denied. Check file's permissions.",
    "ERR_FILE_AUTHORIZATION" : "Authorization Error. Check your login & password.",
    "ERR_FILE_SERVNOEXIST" : "Server Doesn't Exist. Maybe you mistyped it.",
    "ERR_FILE_SERVCANTREACH" : "Can't Reach Server. Check Firewall.",
    "ERR_FILE_FILESIZE0" : "Can't download file. Filesize is 0.",
    "ERR_FILE_DOWNLOAD" : "Can't download file.",
    "ERR_FILE_UPLOAD" : "Can't upload file.",
    "ERR_FILE_DOESNTEXIST" : "File doesn't exist",
    "ERR_FILE_CANTRENAME" : "Can't rename file: ",
    "ERR_FILE_CANTDELETE" : "Can't delete file: ",
    "ERR_FILE_CANTCREATEDIR" : "Can't create folder: ",
    "ERR_FILE_CANTDELETEDIR" : "Can't delete folder: ",
    "ERR_FILE_CANTCREATEFILE" : "Can't create file: ",
    "ERR_FOLDER_OPEN" : "There's an error opening folder as project",

    "CONTEXTM_DOWNLOAD" : "Download",
    "CONTEXTM_UPLOAD" : "Upload",
    "CONTEXTM_ADDQUEUE" : "Add to Queue",
    "CONTEXTM_OPEN" : "Open",
    "CONTEXTM_DELETE" : "Delete",
    "CONTEXTM_RENAME" : "Rename",
    "CONTEXTM_REDOWNLOAD" : "Download from server",
    "CONTEXTM_CREATEFILE" : "Create file",
    "CONTEXTM_CREATEFOLDER" : "Create folder",

    "OTHER_SELECT_SERVER_DROPDOWN" : "Select Remote Server to Connect...",
    "OTHER_ERROR" : "Error",
    "OTHER_PAUSED" : "Paused",
    "OTHER_COMPLETED" : "Completed",
    "OTHER_CANCELLED" : "Cancelled",
    "OTHER_WAITING" : "Waiting",
    "OTHER_YES" : "Yes",
    "OTHER_NO" : "No",
    "OTHER_OK" : "Ok",
    "OTHER_OFF" : "Off",
    "OTHER_CANCEL" : "Cancel",
    "OTHER_APPLY" : "Apply",
    "OTHER_SAVE" : "Save",
    "OTHER_CLOSE" : "Close",
    "OTHER_DELETE" : "Delete",
    "OTHER_CONFIRM_DELETE" : "Are you sure you want to delete this item?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "There are some unsaved changes that will be lost if you click OK.<br>Do you want to proceed?",
    "OTHER_ERROR_EVENDISCONN" : "Can't upload file. 'Even If Disconnected' option is off.",
    "OTHER_ERROR_CANTREADSETTINGS" : "Can't read settings file. You probably mistyped your master password."
});