define({
    "ERR_LOADING" : "Caricamento fallito :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Apri Connection Manager",
    "SIDEPANEL_FILETREE_NAME" : "Nome",
    "SIDEPANEL_FILETREE_SIZE" : "Dim.",
    "SIDEPANEL_FILETREE_TYPE" : "Tipo",
    "SIDEPANEL_FILETREE_MODIFIED" : "Modificato",
    "SIDEPANEL_CONDISCONNECT" : "(Dis)connetti",
    "SIDEPANEL_REFRESH" : "Aggiorna",
    "SIDEPANEL_RELOADSETTINGS" : "Ricarica le impostazioni e reinserisci la password",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "Il Server Non Esiste",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Sembra che questo server non esista. <br>Controlla l'URL del server nelle impostazioni di connessione.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "Non Posso Connettermi Al Server",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "Non posso connettermi al server.<br>Forse il tuo firewall non mi permette di farlo.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Dati Di Autenticazione Errati",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "Non riesco ad autorizzare l'accesso con la login e la password inseriti.<br>Ti prego di verificarli.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "Nessuna connessione specificata",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "Non hai specificato nessuna connessione in eqFTP che associ il tuo progetto corrente ad un server remoto.<br>Specifica un server remoto per la connessione oppure utilizza l'attuale cartella del progetto come percorso locale nelle impostazioni.",
    "ERR_DIAG_ECONNRESET_TITLE" : "Server sta rifiutando le connessioni",
    "ERR_DIAG_ECONNRESET_CONTENT" : "Non riesco a connettermi al server, non mi é permesso.<br>Prova a riavviare Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Sei stato disconnesso dal server",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Connessione interrotta. Provo a riconnettermi...",
    "ERR_DIAG_UNIVERSAL_TITLE" : "C'é un errore",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Guarda questo errore! Come è potuto accadere?",
    "ERR_DIAG_NORSAKEYFOUND" : "Non c'è la chiave RSA in: ",

    "NOT_DIAG_CONNECTED" : "Connesso al server.",
    "NOT_DIAG_DISCONNECTED" : "Disconnesso dal server.",
    "NOT_DIAG_FILESDIFFERENT" : "C'è una differenza tra i file locali e remoti. Clicca qui per ulteriori azioni.",

    "PASSWDWIND_TITLE" : "Inserisci La Master Password",
    "PASSWDWIND_CONTENT" : "La tua Master Password per eqFTP:",

    "CHECKDIFF_TITLE" : "C'è una differenza tra i file",
    "CHECKDIFF_CONTENT" : "Le copie remote e locali dei file sono diverse. Scegli un azione da compiere.",
    "CHECKDIFF_BUTTON_COMPARE" : "Compara file",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Mostra cambiamenti",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Mantieni file locale",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Mantieni file locale per la coda corrente",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Scarica file remoti",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Scarica file remoti per la coda corrente",

    "SETTINGSWIND_TITLE" : "eqFTP Gestore Connessione",
    "SETTINGSWIND_ERR_BLANKS" : "Oh! Qualcosa è andato storto... controlla il contenuto dei campi e riprova.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Qualcosa è andato davvero storto! Non posso scrivere le impostazioni sul file!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "Il percorso che stai cercando di inserire è attualmente in uso da parte di un'altra connessione.",
    "SETTINGSWIND_NOTIF_DONE" : "Detto, fatto! :)",
    "SETTINGSWIND_SAVEDCONN" : "Connessioni FTP Memorizzate",
    "SETTINGSWIND_DELETECONN_HOVER" : "Rimuovi Questa Connessione",
    "SETTINGSWIND_COPYCONN_HOVER" : "Copia questa connessione",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "Non puoi eliminare la connessione in uso",
    "SETTINGSWIND_ADDCONN_HOVER" : "Aggiungi Nuova Connessione",
    "SETTINGSWIND_ADDCONN_STRING" : "Crea Una Nuova Connessione...",
    "SETTINGSWIND_DELETECONNCONF_1" : "Conferma la rimozione della connessione ",
    "SETTINGSWIND_DELETECONNCONF_2" : ".",
    "SETTINGSWIND_OPENGLOBSET" : "Apri Le Impostazioni FTP Globali...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Seleziona una connessione da modificare nella barra laterale o creane una nuova.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Cartella Progetti:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Cartella Dei i Progetti Con i File Scaricati:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Cartella Impostazioni:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Cartella Con il File Delle Impostazioni",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Non Aprire i Progetti Dopo Il Download",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "Master Password",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Nome Connessione:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Inserisci il nome della connessione",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Server:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Tipo Di Protocollo:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Nome utente:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "Utente FTP",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Password:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "Password FTP",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "Chiave RSA",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "Clicca per selezionare la chiave RSA",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Scegli percorso per la chiave RSA",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Percorso Remoto:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Inserisci il percorso remoto alla cartella radice del progetto",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Percorso Locale:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Crea una nuova cartella nella posizione di default se vuoto",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Esegui Upload Dei Files Durante Il Salvataggio",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Aggiungi alla coda in pausa.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Anche Quando Disconnesso",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Questa opzione permette di collegarsi automaticamente ad un server quando un file salvato viene aperto dal server oppure quando si trova dentro il progetto corrente ed il progetto è stato creato da questa estensione FTP. Beh, spero che tu mi abbia capito..",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Aggiungi il percorso al progetto corrente",
    "SETTINGSWIND_GLOB_FRM_TITLE" : "Scegli il metodo di recupero delle cartelle",
    "SETTINGSWIND_GLOB_FRM_LIST" : "Usa il comando LIST",
    "SETTINGSWIND_GLOB_FRM_MLSD" : "Usa il comando MLSD",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Intervallo keep alive:",
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Valore espresso in secondi. Il valore consigliato è 10. Utilizzare zero per vietare il keep alive dei comandi e disconnettersi dal server ogni volta il comando è eseguito.",
    "SETTINGSWIND_GLOB_DEBUG" : "Debug:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Formato data:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Europeo",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Asiatico",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "Eliminazione automatica della coda",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notifiche",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Offset tempo:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Utilizzare questa opzione per impostare il tempo corretto per la colonna modificata",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Connessione",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatizzazione",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Avanzate",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Imposta automatizzazione:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Sincronizzazione",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Classico",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Seleziona cosa sincronizzare",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "Creazione file",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Creazione cartella",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "Aggiornamento file",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Rinomina",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Spostamento",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Eliminazione",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Impostazioni extra",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Verifica la presenza di differenze",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "Quando apri il file locale o remoto",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Lista ignoramenti",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Stessa sintassi di .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Apri i relativi progetti locali dopo lo switching della connessione e viceversa",
    "SETTINGS_NOTIF_RELOADED" : "Impostazioni ricaricate correttamente.",
    "SETTINGS_ERROR_RELOADED" : "Impossibile caricare le impostazioni.",
    "SETTINGSWIND_GLOB_SCE_TITLE" : "Usa i comandi SSH nelle connessioni SFTP",

    "QUEUE_TITLE" : "Coda di eqFTP",
    "QUEUE_HEADER_NAME" : "Nome",
    "QUEUE_HEADER_PATH" : "Percorso",
    "QUEUE_HEADER_FROM" : "Percorso sorgente",
    "QUEUE_HEADER_TO" : "Percorso destinazione",
    "QUEUE_HEADER_STATUS" : "Stato",
    "QUEUE_CLEARQ" : "Ripulisci La Coda",
    "QUEUE_STARTQ" : "Inizia coda",
    "QUEUE_PAUSEQ" : "Pausa coda",
    "QUEUE_RESTARTQ" : "Restart fallito",
    "QUEUE_CONTEXTM_STARTT" : "Start",
    "QUEUE_CONTEXTM_PAUSET" : "Pausa",
    "QUEUE_CONTEXTM_REMOVET" : "Rimuovi",
    "QUEUE_CONTEXTM_RESTARTT" : "Restart",
    "QUEUE_TASK_STATUS_WAITING" : "Aspettando",
    "QUEUE_TASK_STATUS_SUCCESS" : "Fatto",
    "QUEUE_TASK_STATUS_FAIL" : "Fallito",
    "QUEUE_TASK_STATUS_PAUSE" : "In pausa",
    "QUEUE_TASK_STATUS_STARTED" : "Iniziato",
    "QUEUE_TASK_STATUS_DELETED" : "Cancellato",
    "QUEUE_DONT_ADD_COMPLETED" : "Elimina automaticamente task completati",
    
    "ERR_FILE_ACCESSDENIED" : "Accesso Negato. Controlla i permessi del file.",
    "ERR_FILE_AUTHORIZATION" : "Autorizzazione fallita. Controlla la tua login e la tua password.",
    "ERR_FILE_SERVNOEXIST" : "Il Server Non Esiste. Forse hai sbagliato a trascriverlo.",
    "ERR_FILE_SERVCANTREACH" : "Non Posso Collegarmi Al Server. Controlla il Firewall.",
    "ERR_FILE_FILESIZE0" : "Impossibile scaricare il file. La grandezza è 0.",
    "ERR_FILE_DOWNLOAD" : "Impossibile scaricare il file.",
    "ERR_FILE_UPLOAD" : "Impossibile caricare il file.",
    "ERR_FILE_DOESNTEXIST" : "Il file non esiste",
    "ERR_FILE_CANTRENAME" : "Impossibile rinominare il file: ",
    "ERR_FILE_CANTDELETE" : "Impossibile eliminare il file: ",
    "ERR_FILE_CANTCREATEDIR" : "Impossibile creare la cartella: ",
    "ERR_FILE_CANTDELETEDIR" : "Impossibile eliminare la cartella: ",
    "ERR_FILE_CANTCREATEFILE" : "Impossibile creare il file: ",
    "ERR_FOLDER_OPEN" : "C'è un errore nell'apertura della cartella come progetto",

    "CONTEXTM_DOWNLOAD" : "Download",
    "CONTEXTM_UPLOAD" : "Upload",
    "CONTEXTM_ADDQUEUE" : "Aggiungi Alla Coda",
    "CONTEXTM_OPEN" : "Apri",
    "CONTEXTM_DELETE" : "Cancella",
    "CONTEXTM_RENAME" : "Rinnomina",
    "CONTEXTM_REDOWNLOAD" : "Scarica dal server",
    "CONTEXTM_CREATEFILE" : "Crea file",
    "CONTEXTM_CREATEFOLDER" : "Crea cartella",

    "OTHER_SELECT_SERVER_DROPDOWN" : "Seleziona un server remoto...",
    "OTHER_ERROR" : "Errore",
    "OTHER_PAUSED" : "In pausa",
    "OTHER_COMPLETED" : "Completato",
    "OTHER_CANCELLED" : "Cancellato",
    "OTHER_WAITING" : "In attesa",
    "OTHER_YES" : "Si",
    "OTHER_NO" : "No",
    "OTHER_OK" : "Ok",
    "OTHER_OFF" : "Off",
    "OTHER_CANCEL" : "Annulla",
    "OTHER_APPLY" : "Applica",
    "OTHER_SAVE" : "Salva",
    "OTHER_CLOSE" : "Chiudi",
    "OTHER_DELETE" : "Elimina",
    "OTHER_CONFIRM_DELETE" : "Sei sicuro di voler eliminare questo elemento?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "Ci sono delle modifiche non salvate che verranno eliminate se clicchi OK.<br>Vuoi procedere?",
    "OTHER_ERROR_EVENDISCONN" : "Impossibile caricare il file. L'opzione 'Anche se disconnesso' è disabilitata.",
    "OTHER_ERROR_CANTREADSETTINGS" : "Impossibile leggere il file di configurazione. Probabilmente hai sbagliato la tua Master Password."
});
