define({
	"ERR_LOADING" : "Le chargement a échoué :(",

	"SIDEPANEL_TITLE" : "eqFTP",
	"SIDEPANEL_OPENCONNMANGR" : "Ouvrir le gestionnaire de connexion",
	"SIDEPANEL_FILETREE_NAME" : "Nom",
	"SIDEPANEL_FILETREE_SIZE" : "Taille",
	"SIDEPANEL_FILETREE_TYPE" : "Type",
	"SIDEPANEL_FILETREE_MODIFIED" : "Modifié",
	"SIDEPANEL_CONDISCONNECT" : "(Dé)connecter",
	"SIDEPANEL_REFRESH" : "Rafraîchir",
	"SIDEPANEL_RELOADSETTINGS" : "Recharger les paramètres et re-rentrer son mot de passe",

	"ERR_DIAG_SERVNOEXIST_TITLE" : "Le serveur n'existe pas",
	"ERR_DIAG_SERVNOEXIST_CONTENT" : "Il semblerait que ce serveur n'existe pas.<br>Vérifiez les serveurs renseignés dans le gestionnaire de connexion.",
	"ERR_DIAG_SERVCANTREACH_TITLE" : "Impossible d'atteindre le serveur",
	"ERR_DIAG_SERVCANTREACH_CONTENT" : "Je ne peux pas joindre le serveur<br>Peut-être que votre pare-feu m'en empêche.",
	"ERR_DIAG_AUTHORIZEERR_TITLE" : "Accès impossible",
	"ERR_DIAG_AUTHORIZEERR_CONTENT" : "Je ne peux pas vous autoriser l'accès avec le nom d'utilisateur et le mot de passe que vous m'avez fourni.<br>Merci de les vérifier.",
	"ERR_DIAG_NOSERVERFOUND_TITLE" : "Impossible de trouver la connexion",
	"ERR_DIAG_NOSERVERFOUND_CONTENT" : "Il n'y a aucune connexion eqFTP liée à ce projet et aucun serveur connecté.<br>Connectez-vous à un serveur ou précisez le chemin du projet en cours comme chemin local comme connexion dans les paramètres.",
	"ERR_DIAG_ECONNRESET_TITLE" : "Le serveur refuse la connexion",
	"ERR_DIAG_ECONNRESET_CONTENT" : "Je ne peux pas me connecter au serveur, il ne me laisse pas faire.<br>Essayez de redémarrer Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Vous avez été déconnecté du serveur",
	"ERR_DIAG_ECONNABORTED_CONTENT" : "La connexion a échouée... Nouvel essai en cours",
	"ERR_DIAG_UNIVERSAL_TITLE" : "Il y a une erreur",
	"ERR_DIAG_UNIVERSAL_CONTENT" : "Regardez-moi cette erreur ! Comment ça a pu arriver ?",

    "NOT_DIAG_CONNECTED" : "Connecté au serveur.",
    "NOT_DIAG_DISCONNECTED" : "Déconnecté du serveur",
    "NOT_DIAG_FILESDIFFERENT" : "Les fichiers locaux et les fichiers distants sont différents. Cliquez ici pour choisir l'action à effectuer", 
    
	"PASSWDWIND_TITLE" : "Merci de renseigner votre mot de passe",
	"PASSWDWIND_CONTENT" : "Votre mot de passe pour eqFTP:",

    "CHECKDIFF_TITLE" : "There's difference between files",
    "CHECKDIFF_CONTENT" : "Les fichiers locaux et les fichiers distants sont différents. S'il vous plait, choisissez l'action à effectuer",
    "CHECKDIFF_BUTTON_COMPARE" : "Comparer les fichiers",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Afficher les changements",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Garder les fichiers locaux",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Garder des copies locales pour la file d'attente actuelle",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Obtenir des fichiers distants",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Obtenir des copies distantes pour la file d'attente actuelle",

	"SETTINGSWIND_TITLE" : "Gestionnaire de connexion eqFTP",
	"SETTINGSWIND_ERR_BLANKS" : "Oh ! On dirait que quelque chose ne va pas. Vérifiez les champs et ré-essayez.",
	"SETTINGSWIND_ERR_CANTWRITE" : "Quelque chose ne va vraiment pas ! Je ne peux pas sauvegarder les paramètres !",
	"SETTINGSWIND_ERR_LOCALPATHREPEAT" : "Le chemin que vous essayez de renseigner est déjà utilisé par une autre connexion.",
	"SETTINGSWIND_NOTIF_DONE" : "Tout est sauvegardé ! :)",
	"SETTINGSWIND_SAVEDCONN" : "Connexions FTP sauvegardée",
	"SETTINGSWIND_DELETECONN_HOVER" : "Supprimer cette connexion",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "Vous ne pouvez pas supprimer une connexion pendant que vous l'utilisez",
	"SETTINGSWIND_ADDCONN_HOVER" : "Ajouter une nouvelle connexion",
	"SETTINGSWIND_ADDCONN_STRING" : "Créer une nouvelle connexion ...",
	"SETTINGSWIND_DELETECONNCONF_1" : "Veuillez confirmer la suppression de ",
	"SETTINGSWIND_DELETECONNCONF_2" : " connexion(s).",
	"SETTINGSWIND_OPENGLOBSET" : "Ouvrir les paramètres FTP généraux...",
	"SETTINGSWIND_NOTHINGYETMSG" : "Choisissez la connexion à modifier dans la barre latérale ou créez en une nouvelle.",
	"SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Dossier pour vos projets :",
	"SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Chemin pour les projets téléchargés :",
	"SETTINGSWIND_GLOB_FOLDERFORSET" : "Dossier pour vos paramètres:",
	"SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Chemin pour sauvegarder vos paramètres",
	"SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Ne pas ouvrir le projet après le téléchargement",
	"SETTINGSWIND_GLOB_MASTERPASSWORD" : "Mot de passe principal",
	"SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Nom de la connexion :",
	"SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Renseignez le nom de votre connexion",
	"SETTINGSWIND_GLOB_SERVER_TITLE" : "Serveur :",
	"SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Protocole :",
	"SETTINGSWIND_GLOB_USERNAME_TITLE" : "Nom d'utilisateur :",
	"SETTINGSWIND_GLOB_USERNAME_FIELD" : "Nom d'utilisateur FTP",
	"SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Mot de passe:",
	"SETTINGSWIND_GLOB_PASSWORD_FIELD" : "Mot de passe FTP",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "clé RSA",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "Cliquez ici pour choisir la clé RSA",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Choisissez le répertoire de la clé RSA",
	"SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Chemin d'accès distant :",
	"SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Renseignez le chemin d'accès distant à votre projet",
	"SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Chemin d'accès local :",
	"SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Créé un dossier dans chemin par défaut si non renseigné",
	"SETTINGSWIND_GLOB_UPLOADONSAVE" : "Charger les fichiers à la sauvegarde",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Ajouter à la file d'attente en pause",
	"SETTINGSWIND_GLOB_EVENDISCONN" : "Même si deconnecté",
	"SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Cette option vous permet de vous connecter automatiquement au serveur quand le fichier sauvegardé est ouvert depuis le serveur ou que le fichier appartient au projet ouvert et que celui-ci a été créé par cette extension FTP. Oh, j'espère sincèrement que j'ai réussi à me faire comprendre ...",
	"SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Renseignez le chemin du projet actuel",
	"SETTINGSWIND_GLOB_USELIST" : "Alternative folder retrieving",
	"SETTINGSWIND_GLOB_KEEPALIVE" : "Intervalle de connexion persistante:",
	"SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "En secondes. Recommandé à 10s. Utilisez 0 pour désactiver la connexion persistante et se déconnecter à chaque fin de commande.",
	"SETTINGSWIND_GLOB_DEBUG" : "Debug :",
	"SETTINGSWIND_GLOB_TIMEFORMAT" : "Format de date :",
	"SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
	"SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Européen",
	"SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Asiatique",
	"SETTINGSWIND_GLOB_AUTOCLEAR" : "Vider la file d'attente automatiquement",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notifications",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Fuseau horaire:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Utiliser cette option pour paramétrer le bon temps pour les colonnes modifiés",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Connection",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatisation",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Avancé",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Paramétrer l'automatisation :",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Synchronisation",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Classique",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Choisissez quoi synchroniser",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "Création de fichier",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Création de dossier",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "Mise à jour de fichier",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Renommer",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Déplacer",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Supprimer",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Paramètres supplémentaires",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Vérifier les différences",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "Quand vous ouvrez un fichier local ou distant",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Liste ignorée", //NEW
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Même syntaxe que dans .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Ouvrez le projet local associé après avoir échangé les connexions et vice versa",
    "SETTINGS_NOTIF_RELOADED" : "Les paramètres ont été restauré avec succès !",
    "SETTINGS_ERROR_RELOADED" : "Impossible de restaurer les paramètres.", 

    "QUEUE_TITLE" : "File d'attente eqFTP",
    "QUEUE_HEADER_NAME" : "Nom",
    "QUEUE_HEADER_PATH" : "Répertoire",
    "QUEUE_HEADER_FROM" : "Chemin source",
    "QUEUE_HEADER_TO" : "Chemin de destination",
    "QUEUE_HEADER_STATUS" : "Statut",
    "QUEUE_CLEARQ" : "Vider la file d'attente",
    "QUEUE_STARTQ" : "Démarrer la file d'attente",
    "QUEUE_PAUSEQ" : "Mettre en pause la file d'attente",
    "QUEUE_RESTARTQ" : "Le redémarrage à échoué",
    "QUEUE_CONTEXTM_STARTT" : "Démarrer",
    "QUEUE_CONTEXTM_PAUSET" : "Pause",
    "QUEUE_CONTEXTM_REMOVET" : "Enlever",
    "QUEUE_CONTEXTM_RESTARTT" : "Redémarrer",
    "QUEUE_TASK_STATUS_WAITING" : "Attendre",
    "QUEUE_TASK_STATUS_SUCCESS" : "Effectué",
    "QUEUE_TASK_STATUS_FAIL" : "Echoué",
    "QUEUE_TASK_STATUS_PAUSE" : "Mis en pause",
    "QUEUE_TASK_STATUS_STARTED" : "Démarré",
    "QUEUE_TASK_STATUS_DELETED" : "Supprimé",
    "QUEUE_DONT_ADD_COMPLETED" : "Enlever automatiquement les tâches effectuées",
    
    "ERR_FILE_ACCESSDENIED" : "Accès impossible. Vérifiez les droits.",
    "ERR_FILE_AUTHORIZATION" : "Erreur d'autorisation. Vérifiez votre nom d'utilisateur et votre mot de passe.",
    "ERR_FILE_SERVNOEXIST" : "Le serveur n'existe pas. Peut-être l'avez-vous mal écrit.",
    "ERR_FILE_SERVCANTREACH" : "Impossible de joindre le serveur. Vérifiez votre pare-feu.",
    "ERR_FILE_FILESIZE0" : "Impossible de télécharger le fichier. La taille du fichier est de 0kb",
    "ERR_FILE_DOWNLOAD" : "Impossible de télécharger le fichier.",
    "ERR_FILE_UPLOAD" : "Impossible d'envoyer le fichier.",
    "ERR_FILE_DOESNTEXIST" : "Le fichier n'existe pas",
    "ERR_FILE_CANTRENAME" : "Impossible de renommer le fichier : ",
    "ERR_FILE_CANTDELETE" : "Impossible de supprimer le fichier : ",
    "ERR_FILE_CANTCREATEDIR" : "Impossible de créer le dossier : ",
    "ERR_FILE_CANTDELETEDIR" : "Impossible de supprimer le dossier : ",
    "ERR_FILE_CANTCREATEFILE" : "Impossible de créer le fichier : ",
    "ERR_FOLDER_OPEN" : "Il y a eu une erreur en ouvrant le dossier du projet",

	"CONTEXTM_DOWNLOAD" : "Télécharger",
	"CONTEXTM_UPLOAD" : "Charger",
	"CONTEXTM_ADDQUEUE" : "Ajouter à la liste d'attente",
	"CONTEXTM_OPEN" : "Ouvrir",
	"CONTEXTM_DELETE" : "Supprimer",
	"CONTEXTM_RENAME" : "Renommer",
	"CONTEXTM_REDOWNLOAD" : "Télécharger à partir du serveur",
    "CONTEXTM_CREATEFILE" : "Créer un fichier",
    "CONTEXTM_CREATEFOLDER" : "Créer un dossier",

	"OTHER_SELECT_SERVER_DROPDOWN" : "Sélectionnez le serveur distant à ouvrir ...",
	"OTHER_ERROR" : "Erreur",
	"OTHER_PAUSED" : "En pause",
	"OTHER_COMPLETED" : "Terminé",
	"OTHER_CANCELLED" : "Annulé",
	"OTHER_WAITING" : "En attente",
	"OTHER_OK" : "Ok",
    "OTHER_OFF" : "Desactiver",
	"OTHER_CANCEL" : "Annuler",
	"OTHER_APPLY" : "Appliquer",
    "OTHER_SAVE" : "Sauvegarder",
	"OTHER_CLOSE" : "Fermer",
	"OTHER_DELETE" : "Supprimer",
	"OTHER_CONFIRM_DELETE" : "Etes vous sûr de vouloir supprimer cet item ?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "Il y a des changements non sauvegardés qui vont être perdus si vous cliquez sur OK.<br>Voulez vous continuer ?",
	"OTHER_ERROR_EVENDISCONN" : "Impossible d'envoyer le fichier, L'option 'Même si déconnecté' n'est pas activée.",
    "OTHER_ERROR_CANTREADSETTINGS" : "Impossible de lire le fichier de configuration. Vous avez probablement mal tapé votre mot de passe principal."
});
