define({
    "ERR_LOADING" : "Laden mislukt :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Open Verbinding Beheer",
    "SIDEPANEL_FILETREE_NAME" : "Naam",
    "SIDEPANEL_FILETREE_SIZE" : "Grootte",
    "SIDEPANEL_FILETREE_TYPE" : "Type",
    "SIDEPANEL_FILETREE_MODIFIED" : "Aangepast",
    "SIDEPANEL_CONDISCONNECT" : "Verbinden/verbreken",
    "SIDEPANEL_REFRESH" : "Ververs",
    "SIDEPANEL_RELOADSETTINGS" : "Ververs Instellingen & Vul wachtwoord opnieuw in",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "Server bestaat niet",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Het lijkt erop dat de server niet bestaat.<br>Check je server adres.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "Server onbereikbaar",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "Ik kan niet verbinden.<br>Misschien doet je Firewall moeilijk.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Foutieve autorisatiegegevens",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "Ik kan niet inloggen met die gegevens.<br>Controleer ze eens, wil je?",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "Kon verbinding niet vinden",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "Er zijn geen eqFTP verbindingen/server gekoppeld aan dit project.<br>Verbind met de server of stel de momentele projectlocatie in als lokale path voor dit project.",
    "ERR_DIAG_ECONNRESET_TITLE" : "Server staat geen verbindingen toe.",
    "ERR_DIAG_ECONNRESET_CONTENT" : "Ik kan niet verbinden met de server. Het sluit me uit.<br>Probeer Brackets eens te herstarten.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Je bent disconnected van de server",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Verbinding afgebroken. Probeer om opnieuw te verbinden.",
    "ERR_DIAG_UNIVERSAL_TITLE" : "Er heeft zich een fout voorgedaan",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Kijk naar deze fout! Hoe kon dit ooit gebeuren?",
    "ERR_DIAG_NORSAKEYFOUND" : "There's no RSA key found in: ", //NEW A path to RSA file will be appended after colon.

    "NOT_DIAG_CONNECTED" : "Verbonden met de server.",
    "NOT_DIAG_DISCONNECTED" : "Onverbonden met de server.",
    "NOT_DIAG_FILESDIFFERENT" : "Er is een verschil tussen de lokale en externe bestanden. Klik hier voor meer acties.",

    "PASSWDWIND_TITLE" : "Gelieve uw wachtwoord in te voeren",
    "PASSWDWIND_CONTENT" : "Uw wachtwoord voor eqFTP:",

    "CHECKDIFF_TITLE" : "Er is verschil tussen bestanden",
    "CHECKDIFF_CONTENT" : "Externe en lokale kopieën van bestand zinn verschillend. Kies een actie die je zou willen ondernemen",
    "CHECKDIFF_BUTTON_COMPARE" : "Vergelijk bestanden",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Toon veranderingen",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Behoud de lokale",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Behoud lokale kopieën voor de huidige wachtrij",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Krijg extern",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Behoud externe kopieën voor de huidige wachtrij",

    "SETTINGSWIND_TITLE" : "eqFTP Verbinding Beheer",
    "SETTINGSWIND_ERR_BLANKS" : "Oeps! Het lijkt erop dat iets fout is ingevuld. Kijk alles eens na en probeer opnieuw.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Iets liep compleet mis! Ik kon uw instellingen niet schrijven naar een bestand.",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "Het path die u gebruikt wordt momenteel gebruikt door een andere verbinding.",
    "SETTINGSWIND_NOTIF_DONE" : "Alles is opgeslagen! :)",
    "SETTINGSWIND_SAVEDCONN" : "FTP Verbindingen zijn opgeslagen",
    "SETTINGSWIND_DELETECONN_HOVER" : "Verwijder deze verbinding",
    "SETTINGSWIND_COPYCONN_HOVER" : "Kopieer deze verbinding", //NEW
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "Je kunt de huidige verbinding niet verwijderen",
    "SETTINGSWIND_ADDCONN_HOVER" : "Voeg nieuwe verbinding toe",
    "SETTINGSWIND_ADDCONN_STRING" : "Maak nieuwe verbinding aan.",
    "SETTINGSWIND_DELETECONNCONF_1" : "Bevestig de verwijdering van ", // Those 2 strings are going like this: SETTINGSWIND_DELETECONNCONF_1 + VAL + SETTINGSWIND_DELETECONNCONF_2
    "SETTINGSWIND_DELETECONNCONF_2" : ".", // So if in your language there's no need in 2 strings, just leave one of them blank
    "SETTINGSWIND_OPENGLOBSET" : "Open Algemene FTP Instellingen...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Kies verbinding om bij te werken in de zijbalk, of maak een nieuwe.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Map voor projecten:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Map voor projecten met gedownloade bestanden:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Map voor instellingen:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Map voor instellings-bestand:",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Open de projecten NIET na het downloaden",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "Hoofdwachtwoord",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Verbindingsnaam:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Naam van de verbinding",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Server:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Protocol Type:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Gebruikersnaam:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "FTP Gebruikersnaam",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Wachtwoord:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "FTP Wachtwoord",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "RSA sleutel",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "Klik om RSA-sleutel te selecteren",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Kies pad naar RSA-sleutel",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Server Path:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Voer hier de path naar uw project (op de server) in.",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Lokaal Path:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Maakt een nieuwe map aan op standaardlocatie als geen locatie is gegeven",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Upload bestand direct na het opslaan",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Toevoegen aan gepauzeerde wachtrij.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Zelfs als niet verbonden",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Deze optie verbind automatisch met de server zodra er een bestand is geopend van de server of een opgeslagen bestand in het momentele project (indien het project aangemaakt is door deze FTP extentie). Zo, Ik hoop dat deze zin duidelijk was :)",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Voer de locatie van uw project in",
    "SETTINGSWIND_GLOB_FRM_TITLE" : "Kies map ontvang methode:", //NEW
    "SETTINGSWIND_GLOB_FRM_LIST" : "Gebruik LIST command", //NEW
    "SETTINGSWIND_GLOB_FRM_MLSD" : "Gebruik MLSD command", //NEW
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Verbinding-behouden interval:", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Waarde in seconden, standaard 10. Gebruik 0 om geen keep-alive commands te sturen en de verbinding te verbreken na het uitvoeren van een commando.",
    "SETTINGSWIND_GLOB_DEBUG" : "Debug:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Datum formaat:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "Amerikaans",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Europees",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Aziatisch",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "Automatisch legen Queue",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notificaties",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Tijd Offset:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Gebruik deze optie om de juiste tijd in te stelen voor de aangepaste kolom",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Verbinding",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatisering",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Geavanceerd",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Zet automatisering:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Synchronisatie",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Klassiek",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Selecteer wat je wil synchroniseren",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "Bestand creatie",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Map creatie",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "Bestand update",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Hernoemen",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Verplaatsen",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Verwijdering",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Extra instellingen",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Controleer voor verschillen",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "Bij het openen van een lokaal of extern bestand",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Negeer lijst",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Dezelfde syntaxis als in .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Open gerelateerd lokaal project na het inschakelen van verbinding",
    "SETTINGS_NOTIF_RELOADED" : "Instellingen zijn succesvol herladen.",
    "SETTINGS_ERROR_RELOADED" : "Kan instellingen niet herladen.",
    "SETTINGSWIND_GLOB_SCE_TITLE" : "Gebruik SSH command's met SFTP", //NEW

    "QUEUE_TITLE" : "eqFTP Wachtrij",
    "QUEUE_HEADER_NAME" : "Naam",
    "QUEUE_HEADER_PATH" : "Path",
    "QUEUE_HEADER_FROM" : "Oorspronkelijke Path",
    "QUEUE_HEADER_TO" : "Bestemmings Path",
    "QUEUE_HEADER_STATUS" : "Status",
    "QUEUE_CLEARQ" : "Wis Wachtrij",
    "QUEUE_STARTQ" : "Start wachtrij",
    "QUEUE_PAUSEQ" : "Pauzeer wachtrij",
    "QUEUE_RESTARTQ" : "Herstart mislukte",
    "QUEUE_CONTEXTM_STARTT" : "Start",
    "QUEUE_CONTEXTM_PAUSET" : "Pauzeer",
    "QUEUE_CONTEXTM_REMOVET" : "Verwijder", 
    "QUEUE_CONTEXTM_RESTARTT" : "Herstart",
    "QUEUE_TASK_STATUS_WAITING" : "wachten",
    "QUEUE_TASK_STATUS_SUCCESS" : "Klaar",
    "QUEUE_TASK_STATUS_FAIL" : "Gefaald",
    "QUEUE_TASK_STATUS_PAUSE" : "Gepauzeerd",
    "QUEUE_TASK_STATUS_STARTED" : "Gestart",
    "QUEUE_TASK_STATUS_DELETED" : "Verwijderd",
    "QUEUE_DONT_ADD_COMPLETED" : "Automatisch verwijder voltooide taken",
    
    "ERR_FILE_ACCESSDENIED" : "Toegang geweigerd. Controleer bestandsrechten.",
    "ERR_FILE_AUTHORIZATION" : "Autorisatiefout. Controleer je logingegevens.",
    "ERR_FILE_SERVNOEXIST" : "Server bestaat niet. Misschien een spellingsfout?",
    "ERR_FILE_SERVCANTREACH" : "Kon server niet bereiken. Controleer je  Firewall.",
    "ERR_FILE_FILESIZE0" : "Kan bestand niet downloaden. Bestandsgrootte is 0.",
    "ERR_FILE_DOWNLOAD" : "Kan bestand niet downloaden.",
    "ERR_FILE_UPLOAD" : "Kan bestand niet uploaden.",
    "ERR_FILE_DOESNTEXIST" : "Bestand bestaat niet",
    "ERR_FILE_CANTRENAME" : "Kan niet hernoemt worden: ",
    "ERR_FILE_CANTDELETE" : "Kan bestand niet verwijderen: ", 
    "ERR_FILE_CANTCREATEDIR" : "Kan map niet maken: ",
    "ERR_FILE_CANTDELETEDIR" : "Kan map niet verwijderen: ",
    "ERR_FILE_CANTCREATEFILE" : "Kan bestand niet maken: ",
    "ERR_FOLDER_OPEN" : "Er is en fout opgetreden bij het openen van een folder als een project",

    "CONTEXTM_DOWNLOAD" : "Download",
    "CONTEXTM_UPLOAD" : "Upload",
    "CONTEXTM_ADDQUEUE" : "Voeg aan Wachtrij toe",
    "CONTEXTM_OPEN" : "Open",
    "CONTEXTM_DELETE" : "Verwijder",
    "CONTEXTM_RENAME" : "Hernoem",
    "CONTEXTM_REDOWNLOAD" : "Downloaden van server",
    "CONTEXTM_CREATEFILE" : "Maak bestand",
    "CONTEXTM_CREATEFOLDER" : "Maak map",

    "OTHER_SELECT_SERVER_DROPDOWN" : "Selecteer server om te verbinden...",
    "OTHER_ERROR" : "Error",
    "OTHER_PAUSED" : "Gepauzeerd",
    "OTHER_COMPLETED" : "Klaar",
    "OTHER_CANCELLED" : "Gestopt",
    "OTHER_WAITING" : "Wachten...",
    "OTHER_YES" : "Ja", //NEW
    "OTHER_NO" : "Nee", //NEW
    "OTHER_OK" : "Ok",
    "OTHER_OFF" : "Uit",
    "OTHER_CANCEL" : "Stoppen",
    "OTHER_APPLY" : "Aanpassen",
    "OTHER_SAVE" : "Opslaan",
    "OTHER_CLOSE" : "Sluiten",
    "OTHER_DELETE" : "Verwijderen",
    "OTHER_CONFIRM_DELETE" : "Weet je zeker dat je dit item wilt verwijderen?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "Er zijn een aantal niet-opgeslagen wijzigingen die verloren zullen gaan als je op OK klikt. <br>Wil je doorgaan?",
    "OTHER_ERROR_EVENDISCONN" : "Kan bestand niet uploaden. 'Zelfs als niet verbonden' optie is uitgeschakeld.",
    "OTHER_ERROR_CANTREADSETTINGS" : "Kan instellingen niet lezen. Je hebt waarschijnlijk een verkeerd hoofdwachtwoord ingevoert."
});
