define({
	"ERR_LOADING" : "Загрузка не удалась :(",

	"SIDEPANEL_TITLE" : "eqFTP",
	"SIDEPANEL_OPENCONNMANGR" : "Открыть менеджер соединений",
	"SIDEPANEL_FILETREE_NAME" : "Имя",
	"SIDEPANEL_FILETREE_SIZE" : "Размер",
	"SIDEPANEL_FILETREE_TYPE" : "Тип",
	"SIDEPANEL_FILETREE_MODIFIED" : "Дата изменения",
	"SIDEPANEL_CONDISCONNECT" : "(От)соединиться",
	"SIDEPANEL_REFRESH" : "Обновить",
	"SIDEPANEL_RELOADSETTINGS" : "Перезагрузить настройки и ввести заново пароль",

	"ERR_DIAG_SERVNOEXIST_TITLE" : "Сервер не существует",
	"ERR_DIAG_SERVNOEXIST_CONTENT" : "Похоже, что такого сервера не существует.<br>Проверьте поле Сервер в настройках соединения.",
	"ERR_DIAG_SERVCANTREACH_TITLE" : "Не подключиться к серверу",
	"ERR_DIAG_SERVCANTREACH_CONTENT" : "Я просто не могу достать до сервера.<br>Может у вас Файервол мешает.",
	"ERR_DIAG_AUTHORIZEERR_TITLE" : "Неверные данные авторизации",
	"ERR_DIAG_AUTHORIZEERR_CONTENT" : "Я не могу авторизоваться с теми логином и паролем, которые вы мне дали.<br>Пожалуйста проверьте их.",
	"ERR_DIAG_NOSERVERFOUND_TITLE" : "Не могу найти соединение",
	"ERR_DIAG_NOSERVERFOUND_CONTENT" : "К этому проекту не привязано eqFTP соединение или нет установленного соединения.<br>Подключитесь к серверу или укажите текущую папку проекта как \"Путь к проекту на ПК\" в настройках eqFTP.",
	"ERR_DIAG_ECONNRESET_TITLE" : "Сервер отклоняет соединения",
	"ERR_DIAG_ECONNRESET_CONTENT" : "Я не могу подключиться к серверу, он мне не дает.<br>Попробуйте перезапустить Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Вы были отключены от сервера",
	"ERR_DIAG_ECONNABORTED_CONTENT" : "Соединение разорвано. Пытаюсь переподключиться...",
	"ERR_DIAG_UNIVERSAL_TITLE" : "Ошибка",
	"ERR_DIAG_UNIVERSAL_CONTENT" : "Посмотри на эту ошибку! Как это могло произойти?",

    "NOT_DIAG_CONNECTED" : "Подключился к серверу.",
    "NOT_DIAG_DISCONNECTED" : "Отключился от сервера.",
    
	"PASSWDWIND_TITLE" : "Введите пароль",
	"PASSWDWIND_CONTENT" : "Введите пароль к eqFTP:",

	"SETTINGSWIND_TITLE" : "Менеджер соединений eqFTP",
	"SETTINGSWIND_ERR_BLANKS" : "Оу! Кажется, что-то пошло не так. Проверьте поля ввода и попробуйте снова.",
	"SETTINGSWIND_ERR_CANTWRITE" : "Что-то пошло совсем не так! Я не могу записать настройки в файл!",
	"SETTINGSWIND_ERR_LOCALPATHREPEAT" : "Путь, который вы пытаетесь использовать в данный момент используется другим соединением.",
	"SETTINGSWIND_NOTIF_DONE" : "Все сохранено! :)",
	"SETTINGSWIND_SAVEDCONN" : "Сохраненные FTP соединения",
	"SETTINGSWIND_DELETECONN_HOVER" : "Удалить это соединение",
	"SETTINGSWIND_ADDCONN_HOVER" : "Добавить новое соединение",
	"SETTINGSWIND_ADDCONN_STRING" : "Создать новое соединение...",
	"SETTINGSWIND_DELETECONNCONF_1" : "Подтвердите удаление соединения ",
	"SETTINGSWIND_DELETECONNCONF_2" : ".",
	"SETTINGSWIND_OPENGLOBSET" : "Открыть общие настройки eqFTP...",
	"SETTINGSWIND_NOTHINGYETMSG" : "Выберите соединение для редактирования в панели слева или создайте новое.",
	"SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Папка проектов:",
	"SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Папка с проектами, куда будут сохраняться загруженные файлы:",
	"SETTINGSWIND_GLOB_FOLDERFORSET" : "Папка настроек:",
	"SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Папка, куда будет сохраняться файл с настройками",
	"SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Не открыть проекты после загрузки файлов",
	"SETTINGSWIND_GLOB_STORESAFELY" : "Сохранять пароли зашифрованно",
	"SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Название соединения:",
	"SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Введите имя соединения",
	"SETTINGSWIND_GLOB_SERVER_TITLE" : "Сервер:",
	"SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Тип протокола:",
	"SETTINGSWIND_GLOB_USERNAME_TITLE" : "Имя пользователя:",
	"SETTINGSWIND_GLOB_USERNAME_FIELD" : "Имя FTP пользователя",
	"SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Пароль:",
	"SETTINGSWIND_GLOB_PASSWORD_FIELD" : "Пароль к FTP",
	"SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Удаленный путь:",
	"SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Введите путь, который будет открываться по умолчанию",
	"SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Путь к проекту на ПК:",
	"SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Если оставить пустым, создает новую папку в стандартном месте",
	"SETTINGSWIND_GLOB_UPLOADONSAVE" : "Загружать файлы после сохранения",
	"SETTINGSWIND_GLOB_EVENDISCONN" : "Даже, если не подключен к FTP",
	"SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Эта опция дает вам возможность загружать только что сохраненные файлы, если этот файл находится в проекте, который был создан или связан с FTP соединением, или если этот файл был загружен с FTP. Надеюсь, я нормально объяснил..",
	"SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Вставить путь к текущему проекту",
	"SETTINGSWIND_GLOB_USELIST": "Альтернативный способ получения папок",
	"SETTINGSWIND_GLOB_KEEPALIVE" : "Keep alive интервал",
	"SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Значение в секундах. Рекомендуемое значение - 10. Используйте ноль, чтобы запретить keep alive команды и отключаться от сервера сразу после завершения команды.",
	"SETTINGSWIND_GLOB_DEBUG" : "Отладка:",
	"SETTINGSWIND_GLOB_TIMEFORMAT" : "Формат даты:",
	"SETTINGSWIND_GLOB_TIMEFORMAT_US" : "США",
	"SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Европейский",
	"SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Азиатский",
	"SETTINGSWIND_GLOB_SYNC" : "Синхронизировать",
	"SETTINGSWIND_GLOB_SYNC_DESC" : "Будет удалять или переименовывать файл после изменения этого файла в Brackets.",
	"SETTINGSWIND_GLOB_AUTOCLEAR" : "Автоочистка очереди",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Оповещения",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Смещение по времени:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Используйте этот параметр для настройки правильного отображения времени изменения файла",

	"QUEUE_TITLE" : "eqFTP очередь",
	"QUEUE_TITLE_HOVER" : "Нажмите, чтобы открыть eqFTP очередь",
	"QUEUE_HEADER_NAME" : "Имя",
	"QUEUE_HEADER_PATH" : "Путь",
	"QUEUE_HEADER_FROM" : "Исходный путь",
	"QUEUE_HEADER_TO" : "Путь назначения",
	"QUEUE_HEADER_STATUS" : "Статус",
	"QUEUE_REMOVE" : "Удалить из очереди",
	"QUEUE_CONTEXTM_STARTQ" : "Запустить задание",
	"QUEUE_CONTEXTM_PAUSEQ" : "Приостановить",
	"QUEUE_CONTEXTM_CLEARQ" : "Очистить очередь",
	"QUEUE_CONTEXTM_CLEARCOMPQ" : "Очистить завершенные задания",
	"QUEUE_CONTEXTM_CLEARFAILQ" : "Очистить неудавшиеся задания",
	"QUEUE_CONTEXTM_CLEARPAUSQ" : "Очистить приостановленные задания",
	"QUEUE_CONTEXTM_RESTARTFAILQ" : "Перезапустить неудавшиеся задания",
	"QUEUE_DONT_ADD_COMPLETED" : "Автоматически очищать завершенное",
	"ERR_FILE_ACCESSDENIED" : "Доступ запрещен. Проверьте доступ к файлу.",
	"ERR_FILE_AUTHORIZATION" : "Ошибка авторизации. Проверьте логин и пароль.",
	"ERR_FILE_SERVNOEXIST" : "Сервер не существует. Может, вы опечатались.",
	"ERR_FILE_SERVCANTREACH" : "Не могу подключиться к серверу. Проверьте Файервол.",
	"ERR_FILE_FILESIZE0" : "Не могу скачать файл. Размер файла равен 0.",
    "ERR_FILE_DOWNLOAD" : "Не могу скачать файл.",
    "ERR_FILE_DOESNTEXIST" : "Файл не существует",
    "ERR_FOLDER_OPEN" : "При открытии папки в качестве проекта произошла ошибка",

	"CONTEXTM_DOWNLOAD" : "Загрузить с FTP",
	"CONTEXTM_UPLOAD" : "Загрузить на FTP",
	"CONTEXTM_ADDQUEUE" : "Добавить в очередь",
	"CONTEXTM_OPEN" : "Открыть",
	"CONTEXTM_DELETE" : "Удалить",
	"CONTEXTM_RENAME" : "Переименовать",
	"CONTEXTM_REDOWNLOAD" : "Скачать с сервера",

	"OTHER_SELECT_SERVER_DROPDOWN" : "Выберите сервер для подключения...",
	"OTHER_ERROR" : "Ошибка",
	"OTHER_PAUSED" : "Приостановлено",
	"OTHER_COMPLETED" : "Завершено",
	"OTHER_CANCELLED" : "Отменено",
	"OTHER_WAITING" : "Ожидание",
	"OTHER_OK" : "Ок",
	"OTHER_CANCEL" : "Отмена",
	"OTHER_APPLY" : "Применить",
	"OTHER_CLOSE" : "Закрыть",
	"OTHER_DELETE" : "Удалить",
	"OTHER_CONFIRM_DELETE" : "Вы уверены, что хотите удалить этот элемент?",
	"OTHER_ERROR_EVENDISCONN" : "Не могу загрузить файл. Опция 'Даже, если не подключен к FTP' не включена.",
});