define({
    "ERR_LOADING" : "Yükleme başarısız :(",
    
    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Bağlantı Yöneticisini Aç",
    "SIDEPANEL_FILETREE_NAME" : "İsim",
    "SIDEPANEL_FILETREE_SIZE" : "Boyut",
    "SIDEPANEL_FILETREE_TYPE" : "Tip",
    "SIDEPANEL_FILETREE_MODIFIED" : "Düzenlenme",
    "SIDEPANEL_CONDISCONNECT" : "Bağlan/Bağlantıyı kes",
    "SIDEPANEL_REFRESH" : "Yenile",
    "SIDEPANEL_RELOADSETTINGS" : "Şifre ile Ayarları Yenile",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "Sunucu Bulunamadı",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Bu sunucu bulunamamış gözüküyor.<br>Bağlantı ayarlarında sunucu bilgilerini girdiğinden emin ol.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "Sunucuya Ulaşılamıyor",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "Şuan sunucuya ulaşılamıyor.<br>Buna Firewall engel olmuş olabilir.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Yetkilendirme Bilgileri Yanlış",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "Girdiğiniz kullanıcı adı ve şifre için yetkilendirme yapılamadı.<br>Lütfen kontrol edin.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "Bağlantı Yok",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "Güncel projeye bağlı eqFTP bağlantısı yok veya sunucuya bağlı değil.<br>Sunucuya bağlanın veya ayarlarda yerel yol olarak güncel proje klasörünü belirleyin.",
    "ERR_DIAG_ECONNRESET_TITLE" : "Sunucu bağlantıyı reddediyor",
    "ERR_DIAG_ECONNRESET_CONTENT" : "Sunucuya bağlanılamadı, buna izin yok.<br>Brackets'ı yeniden başlatmayı deneyin.",
    "ERR_DIAG_UNIVERSAL_TITLE" : "Bir sorun var!",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Sanırım bir hata oluştu! Bu nasıl oldu?",
    
    "PASSWDWIND_TITLE" : "Lütfen Şifrenizi Girin",
    "PASSWDWIND_CONTENT" : "eqFTP için Şifreniz:",
    
    "SETTINGSWIND_TITLE" : "eqFTP Bağlantı Yöneticisi",
    "SETTINGSWIND_ERR_BLANKS" : "Oh! Birşeyler ters gidiyor gibi. Girdiğiniz bilgileri kontrol edip, tekrar deneyin.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Bazı şeyler tamamen ters gitti! Ayarlar dosyasına yazamadım!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "Ekleme yapmak istediğin yol, başka bir bağlantı tarafından kullanılıyor.",
    "SETTINGSWIND_NOTIF_DONE" : "Ayarlar kaydedildi! :)",
    "SETTINGSWIND_SAVEDCONN" : "Kayıtlı FTP Bağlantıları",
    "SETTINGSWIND_DELETECONN_HOVER" : "Bu Bağlantıyı Sil",
    "SETTINGSWIND_ADDCONN_HOVER" : "Yeni Bağlantı Ekle",
    "SETTINGSWIND_ADDCONN_STRING" : "Yeni Bağlantı Oluştur...",
    "SETTINGSWIND_DELETECONNCONF_1" : "",
    "SETTINGSWIND_DELETECONNCONF_2" : " adlı bağlantı silinsin mi?",
    "SETTINGSWIND_OPENGLOBSET" : "eqFTP Ayarları",
    "SETTINGSWIND_NOTHINGYETMSG" : "Kenar Çubuğunda düzenlemek için bir bağlantı seçin veya yeni oluşturun.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Projeler için Klasör:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Projeler ve İndirilen Dosyalar için Klasör:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Ayarlar için Klasör:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Ayar Dosyaları için Klasör",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "İndirdikten Sonra Projeyi Açma",
    "SETTINGSWIND_GLOB_STORESAFELY" : "Şifreyi Güvende Tut",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Bağlantı İsmi:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Bağlantı ismini girin",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Sunucu:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Protokol Tipi:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Kullanıcı Adı:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "FTP kullanıcı adı",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Şifre:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "FTP şifre",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Sunucu Yolu:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Uzak sunucuda projenizin ana dizininin bulunduğu klasörü girin",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Yerel Yol:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Eğer boş bırakırsanız varsayılan konumunuza yeni klasör oluşturur",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Dosya Kaydedildiğinde Yükle",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Bağlı Olmadığında Bile",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Bu seçenek ile sunucuya otomatik bağlanılarak, sunucu üzerinden açılan dosyalar hemen yüklenir veya sunucuda yeni bir dosya oluşturulur.",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Geçerli projenin yolunu ekle",
    "SETTINGSWIND_GLOB_USELIST" : "Geri alma için alternatif klasör",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Canlı Tutma Aralığı",
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Saniye cinsinden değer. Önerilen değer 10'dur. Komutları canlı tutmayı yasaklamak için 0'ı kullan ve her komut kullanıldığında sunucuyla bağlantısını kes",
    "SETTINGSWIND_GLOB_DEBUG" : "Debug:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Tarih Formatı:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "ABD",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Avrupa",
    "SETTINGSWIND_GLOB_SYNC" : "Senkronizasyon",
    "SETTINGSWIND_GLOB_SYNC_DESC" : "Dosyalar Brackets'ta silindiğinde veya ismi değiştirildiğinde, uzak sunucuda da aynı işlem uygulanacak.",
    
    "QUEUE_TITLE" : "eqFTP Kuyruğu",
    "QUEUE_TITLE_HOVER" : "eqFTP Kuyruğunu Açmak İçin Tıklayın",
    "QUEUE_HEADER_NAME" : "İsim",
    "QUEUE_HEADER_PATH" : "Yol",
    "QUEUE_HEADER_FROM" : "Kaynak Yolu",
    "QUEUE_HEADER_TO" : "Hedef Yolu",
    "QUEUE_HEADER_STATUS" : "Durum",
    "QUEUE_REMOVE" : "Kuyruktan Sil",
    "QUEUE_CONTEXTM_STARTQ" : "Görevi Başlat",
    "QUEUE_CONTEXTM_PAUSEQ" : "Görevi Durdur",
    "QUEUE_CONTEXTM_CLEARQ" : "Kuyruğu Temizle",
    "QUEUE_CONTEXTM_CLEARCOMPQ" : "Tamamlanan Görevleri Sil",
    "QUEUE_CONTEXTM_CLEARFAILQ" : "Tamamlanamayan Görevleri Sil",
    "QUEUE_CONTEXTM_RESTARTFAILQ" : "Tamamlanamayan Görevleri Yeniden Başlat",
    "ERR_FILE_ACCESSDENIED" : "Erişim Reddedildi. Dosya izinlerini kontrol edin.",
    "ERR_FILE_AUTHORIZATION" : "Yetkilendirme Hatası. Kullanıcı adı ve şifre bilgilerinizi kontrol edin.",
    "ERR_FILE_SERVNOEXIST" : "Sunucu Yok. Belkide yanlış yazmışsınızdır.",
    "ERR_FILE_SERVCANTREACH" : "Sunucuya ulaşılamadı. Firewall'ı kontrol edin.",
    
    "CONTEXTM_DOWNLOAD" : "İndir",
    "CONTEXTM_UPLOAD" : "Yükle",
    "CONTEXTM_ADDQUEUE" : "Kuyruğa Ekle",
    "CONTEXTM_OPEN" : "Aç",
    "CONTEXTM_DELETE" : "Sil",
    "CONTEXTM_RENAME" : "İsmini Değiştir",
    
    "OTHER_SELECT_SERVER_DROPDOWN" : "Bağlanmak için bir Bağlantı Seçin",
    "OTHER_ERROR" : "Hata",
    "OTHER_PAUSED" : "Durduruldu",
    "OTHER_COMPLETED" : "Tamamlandı",
    "OTHER_CANCELLED" : "İptal Edildi",
    "OTHER_WAITING" : "Bekleniyor",
    "OTHER_OK" : "Tamam",
    "OTHER_CANCEL" : "İptal",
    "OTHER_APPLY" : "Uygula",
    "OTHER_CLOSE" : "Kapat",
    "OTHER_DELETE" : "Sil",
});
