define({
    "ERR_LOADING" : "読込に失敗しました。",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "接続マネージャーを開く",
    "SIDEPANEL_FILETREE_NAME" : "名前",
    "SIDEPANEL_FILETREE_SIZE" : "サイズ",
    "SIDEPANEL_FILETREE_TYPE" : "種類",
    "SIDEPANEL_FILETREE_MODIFIED" : "変更",
    "SIDEPANEL_CONDISCONNECT" : "接続解除",
    "SIDEPANEL_REFRESH" : "更新",
    "SIDEPANEL_RELOADSETTINGS" : "設定再読込とパスワード再入力",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "サーバーがありません。",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "このサーバーは存在しないようです。<br>接続設定を確認してください。",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "サーバーに接続できません。",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "ファイアーウォールが原因で接続できない可能性があります。",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "認証情報が間違っています。",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "指定したアカウントでログインできませんでした。",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "サーバーが見つかりません。",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "eqFTP サーバーが見つかりません。<br>プロジェクトフォルダの接続設定を確認してください。",
    "ERR_DIAG_ECONNRESET_TITLE" : "サーバーが接続を拒否しました",
    "ERR_DIAG_ECONNRESET_CONTENT" : "サーバーに接続できませんでした。Brackets を再起動してみてください。",
    "ERR_DIAG_ECONNABORTED_TITLE" : "サーバーから切断されました", //NEW
    "ERR_DIAG_ECONNABORTED_CONTENT" : "接続が中断されました。再試行中です。", //NEW
    "ERR_DIAG_UNIVERSAL_TITLE" : "不明なエラー",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "不明なエラーが発生しました。",

    "NOT_DIAG_CONNECTED" : "接続完了です。",
    "NOT_DIAG_DISCONNECTED" : "接続解除されました。",
    "NOT_DIAG_FILESDIFFERENT" : "ローカルとリモートファイルの差分です。詳細はクリックしてください。", //NEW

    "PASSWDWIND_TITLE" : "パスワードを入力してください",
    "PASSWDWIND_CONTENT" : "パスワード:",

    "CHECKDIFF_TITLE" : "ファイル差分",
    "CHECKDIFF_CONTENT" : "リモートとローカルのファイル差分です。詳細はクリックしてください。",
    "CHECKDIFF_BUTTON_COMPARE" : "ファイル比較",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "相違点の表示",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "ローカルを保存",
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "ローカルファイルを保持します。",
    "CHECKDIFF_BUTTON_GETREMOTE" : "リモートを取得",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "リモートファイルを取得します。",

    "SETTINGSWIND_TITLE" : "eqFTP 接続マネージャー",
    "SETTINGSWIND_ERR_BLANKS" : "空欄の項目があります。",
    "SETTINGSWIND_ERR_CANTWRITE" : "設定内容を保存できませんでした。",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "指定されたパスは他の接続で使用中です。",
    "SETTINGSWIND_NOTIF_DONE" : "保存しました。",
    "SETTINGSWIND_SAVEDCONN" : "FTP 設定を保存しました。",
    "SETTINGSWIND_DELETECONN_HOVER" : "接続を削除しました。",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "使用中の接続は削除できません。",
    "SETTINGSWIND_ADDCONN_HOVER" : "新しい接続",
    "SETTINGSWIND_ADDCONN_STRING" : "新しい接続",
    "SETTINGSWIND_DELETECONNCONF_1" : "削除してもよろしいですか。", // Those 2 strings are going like this: SETTINGSWIND_DELETECONNCONF_1 + VAL + SETTINGSWIND_DELETECONNCONF_2
    "SETTINGSWIND_DELETECONNCONF_2" : " 接続", // So if in your language there's no need in 2 strings, just leave one of them blank
    "SETTINGSWIND_OPENGLOBSET" : "FTP 全般設定",
    "SETTINGSWIND_NOTHINGYETMSG" : "サイドバーから編集する接続を選択するか、接続を作成してください。",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "プロジェクトのフォルダ:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "ダウンロードされたファイルのディレクトリ",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "設定のフォルダ:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "設定用ファイルのディレクトリ",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "ダウンロード後にプロジェクトを開かないでください。",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "マスターパスワード",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "接続名:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "接続に名前をつけます。",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "サーバー:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "プロトコル:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "ユーザー名:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "FTP のユーザー名です。",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "パスワード:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "FTP のパスワードです。",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "RSA キー",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "クリックして RSA キーを選択肢",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "RSA キーのパス",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "リモートパス:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "リモートサーバーのパスです。",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "ローカルパス:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "ローカスパスです。無指定の場合は空のフォルダが作成されます。",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "保存時にアップロードする。",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "保留キューに追加",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "オフラインフォルダ",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "サーバーへのダウンロードや編集時に一時的に保存されるプロジェクトフォルダです。うまく説明できたかな？",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "現在のプロジェクトのタイトル",
    "SETTINGSWIND_GLOB_USELIST" : "代替フォルダ",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "キープアライブの間隔", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "秒単位で指定します。おすすめは10病です。0 を指定するとコマンド実行後にすぐ接続解除します。.",
    "SETTINGSWIND_GLOB_DEBUG" : "デバッグ:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "日付形式:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "米国",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "欧米",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "アジア",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "キューの自動クリア",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "通知",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "タイムオフセット:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "更新時間を修正する場合に指定します。",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "接続",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "自動化",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "高度な設定",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "自動化設定:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "同期",
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Classic",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "同期対象を選択",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "ファイル作成",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "フォルダ作成",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "ファイルアップロード",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "リネーム中",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "移動中",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "削除中",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "拡張設定",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "相違箇所のチェック",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "ローカルまたはリモートのファイルを開いた時に相違チェックします。",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : ".gitignore を無視",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : ".gitignore ファイルを無視します。",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "接続を切り替えた時にプロジェクトを自動的に開きます。", //NEW
    "SETTINGS_NOTIF_RELOADED" : "設定は正常にリロードされました。", //NEW
    "SETTINGS_ERROR_RELOADED" : "設定をリロードできませんでした。", //NEW

    "QUEUE_TITLE" : "eqFTP キュー",
    "QUEUE_HEADER_NAME" : "名前",
    "QUEUE_HEADER_PATH" : "パス",
    "QUEUE_HEADER_FROM" : "反映元",
    "QUEUE_HEADER_TO" : "反映先",
    "QUEUE_HEADER_STATUS" : "状態",
    "QUEUE_CLEARQ" : "キューのクリア",
    "QUEUE_STARTQ" : "タスク開始",
    "QUEUE_PAUSEQ" : "タスク保留",
    "QUEUE_RESTARTQ" : "キューの再開",
    "QUEUE_CONTEXTM_STARTT" : "開始",
    "QUEUE_CONTEXTM_PAUSET" : "保留",
    "QUEUE_CONTEXTM_REMOVET" : "削除",
    "QUEUE_CONTEXTM_RESTARTT" : "失敗したタスクの再開",
    "QUEUE_TASK_STATUS_WAITING" : "待機中",
    "QUEUE_TASK_STATUS_SUCCESS" : "完了",
    "QUEUE_TASK_STATUS_FAIL" : "失敗",
    "QUEUE_TASK_STATUS_PAUSE" : "保留",
    "QUEUE_TASK_STATUS_STARTED" : "開始されました",
    "QUEUE_TASK_STATUS_DELETED" : "削除されました",
    "QUEUE_DONT_ADD_COMPLETED" : "自動クリア完了",

    "ERR_FILE_ACCESSDENIED" : "アクセス拒否。ファイルの権限を確認してください。",
    "ERR_FILE_AUTHORIZATION" : "認証失敗。アカウントを確認してください。",
    "ERR_FILE_SERVNOEXIST" : "サーバーが見つかりません。サーバー名を確認してください。",
    "ERR_FILE_SERVCANTREACH" : "サーバーに到達できません。ファイアウォールの設定を確認してください。",
    "ERR_FILE_FILESIZE0" : "ファイルが空のためダウンロードできません。", //NEW
    "ERR_FILE_DOWNLOAD" : "ダウンロードできません。", //NEW
    "ERR_FILE_UPLOAD" : "ファイルをアップロードできません。",
    "ERR_FILE_DOESNTEXIST" : "ファイルが存在しません。", //NEW
    "ERR_FILE_CANTRENAME" : "リネームできません。: ",
    "ERR_FILE_CANTDELETE" : "削除できません。: ",
    "ERR_FILE_CANTCREATEDIR" : "フォルダを作成できません。: ",
    "ERR_FILE_CANTDELETEDIR" : "フォルダを削除できません。: ",
    "ERR_FILE_CANTCREATEFILE" : "ファイルを作成できません。: ", //NEW
    "ERR_FOLDER_OPEN" : "プロジェクトフォルダを開けません。", //NEW

    "CONTEXTM_DOWNLOAD" : "ダウンロード",
    "CONTEXTM_UPLOAD" : "アップロード",
    "CONTEXTM_ADDQUEUE" : "キューに追加",
    "CONTEXTM_OPEN" : "開く",
    "CONTEXTM_DELETE" : "削除",
    "CONTEXTM_RENAME" : "リネーム",
    "CONTEXTM_REDOWNLOAD" : "サーバーからダウンロード",
    "CONTEXTM_CREATEFILE" : "ファイル作成", //NEW
    "CONTEXTM_CREATEFOLDER" : "フォルダ作成", //NEW

    "OTHER_SELECT_SERVER_DROPDOWN" : "接続先を選択...",
    "OTHER_ERROR" : "エラー",
    "OTHER_PAUSED" : "停止中",
    "OTHER_COMPLETED" : "完了",
    "OTHER_CANCELLED" : "取消",
    "OTHER_WAITING" : "待機中",
    "OTHER_OK" : "OK",
    "OTHER_OFF" : "OFF",
    "OTHER_CANCEL" : "キャンセル",
    "OTHER_APPLY" : "適用",
    "OTHER_SAVE" : "保存",
    "OTHER_CLOSE" : "閉じる",
    "OTHER_DELETE" : "削除",
    "OTHER_CONFIRM_DELETE" : "このアイテムを削除しますか?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "OK を押すと変更内容が破棄されます。<br>よろしいですか?",
    "OTHER_ERROR_EVENDISCONN" : "オフライン設定されていないため、アップロードできません。",
    "OTHER_ERROR_CANTREADSETTINGS" : "設定ファイルを読込できませんでした。マスターパスワードが間違っている可能性があります。"
});
