define({
	"ERR_LOADING" : "Sikertelen betöltés :(",

	"SIDEPANEL_TITLE" : "eqFTP",
	"SIDEPANEL_OPENCONNMANGR" : "Kapcsolatkezelő megnyitása",
	"SIDEPANEL_FILETREE_NAME" : "Név",
	"SIDEPANEL_FILETREE_SIZE" : "Méret",
	"SIDEPANEL_FILETREE_TYPE" : "Típus",
	"SIDEPANEL_FILETREE_MODIFIED" : "Módosítva",
	"SIDEPANEL_CONDISCONNECT" : "Kapcsolódás/Bezárás",
	"SIDEPANEL_REFRESH" : "Frissítés",
	"SIDEPANEL_RELOADSETTINGS" : "Beállítások újratöltése és jelszó újra megadása",

	"ERR_DIAG_SERVNOEXIST_TITLE" : "Szerver nem található",
	"ERR_DIAG_SERVNOEXIST_CONTENT" : "A szerver nem található.<br>Kérlek ellenőrizd a beállításokat",
	"ERR_DIAG_SERVCANTREACH_TITLE" : "A szervert nem sikerült elérni.",
	"ERR_DIAG_SERVCANTREACH_CONTENT" : "Nem tudom elérni a szervert.<br>Lehetséges, hogy a tűzfal akadályozza ezt meg.",
	"ERR_DIAG_AUTHORIZEERR_TITLE" : "Hibás hitelesítő adatok",
	"ERR_DIAG_AUTHORIZEERR_CONTENT" : "Hibás felhasználónév vagy jelszó.<br>Kérlek ellenőrizd őket.",
	"ERR_DIAG_NOSERVERFOUND_TITLE" : "Nincsenek kapcsolatok-Can't find connection",
	"ERR_DIAG_NOSERVERFOUND_CONTENT" : "Nincs beállítva kapcsolat amit használni tudnék.<br>Kapcsolódj egy szerverhez vagy adj meg egy helyi projekt könyvtárat kapcsolatként a Beállítások menüpontban.",
	"ERR_DIAG_ECONNRESET_TITLE" : "A szerver visszautasította a kapcsolódást",
	"ERR_DIAG_ECONNRESET_CONTENT" : "Nem tudok kapcsolódni a szerverhez, mert az visszautasította a kérést.<br>Tipp: Próbáld újraindítani a programot.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Kapcsolódás megszakítva",
	"ERR_DIAG_ECONNABORTED_CONTENT" : "Kapcsolódás megszakítva. Újrapróbálkozás...",
	"ERR_DIAG_UNIVERSAL_TITLE" : "HIBA!",
	"ERR_DIAG_UNIVERSAL_CONTENT" : "Sajnos általános hiba történt. :(",
    
    "NOT_DIAG_CONNECTED" : "Kapcsolódva.",
    "NOT_DIAG_DISCONNECTED" : "Kapcsolat bontva.",

	"PASSWDWIND_TITLE" : "Kérlek írd be az FTP jelszavad",
	"PASSWDWIND_CONTENT" : "FTP jelszó:",

	"SETTINGSWIND_TITLE" : "eqFTP Kapcsolatkezelő",
	"SETTINGSWIND_ERR_BLANKS" : "Hopp! Úgy tűnik valami nincs rendben. Kérlek töltsd ki a mezőket és próbáld újra!",
	"SETTINGSWIND_ERR_CANTWRITE" : "Valami hiba történt. Nem tudom elmenteni a beállításokat!",
	"SETTINGSWIND_ERR_LOCALPATHREPEAT" : "Az útvonalat jelenleg egy másik kapcsolat használja.",
	"SETTINGSWIND_NOTIF_DONE" : "Grat! Minden mentve! :)",
	"SETTINGSWIND_SAVEDCONN" : "Mentett kapcsolatok",
	"SETTINGSWIND_DELETECONN_HOVER" : "Kapcsolat törlése",
	"SETTINGSWIND_ADDCONN_HOVER" : "Új kapcsolat",
	"SETTINGSWIND_ADDCONN_STRING" : "Új kapcsolat létrehozása...",
	"SETTINGSWIND_DELETECONNCONF_1" : "Kérlek erősítsd meg a ",
	"SETTINGSWIND_DELETECONNCONF_2" : " kapcsolat törlését.",
	"SETTINGSWIND_OPENGLOBSET" : "Globális FTP beállítások megnyitása...",
	"SETTINGSWIND_NOTHINGYETMSG" : "Válaszd ki a módosítani kívánt kapcsolatot vagy az oldalsávon hozz létre egyet.",
	"SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Folder For Projects:",                                        // I can't translate right now
	"SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Directory for Projects with Downloaded Files:",     // I can't translate right now
	"SETTINGSWIND_GLOB_FOLDERFORSET" : "Folder For Settings:",                                         // I can't translate right now
	"SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Directory for Settings File",                        // I can't translate right now
	"SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Ne nyisd meg a projekteket a letöltés után",
	"SETTINGSWIND_GLOB_STORESAFELY" : "Jelszó biztonságos tárolása",
	"SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Kapcsolat neve:",
	"SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Írd be a kapcsolat nevét",
	"SETTINGSWIND_GLOB_SERVER_TITLE" : "Szerver:",
	"SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Protokoll:",
	"SETTINGSWIND_GLOB_USERNAME_TITLE" : "Felhasználónév:",
	"SETTINGSWIND_GLOB_USERNAME_FIELD" : "FTP felhasználónév",
	"SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Jelszó:",
	"SETTINGSWIND_GLOB_PASSWORD_FIELD" : "FTP jelszó",
	"SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Távoli útvonal:",
	"SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Type in the remote path to the project root folder",       // I can't translate right now
	"SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Helyi útvonal:",
	"SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Ha üres, az alapértelmezett könyvtárban lesz létrehozva",
	"SETTINGSWIND_GLOB_UPLOADONSAVE" : "Mentéskor feltöltés",
	"SETTINGSWIND_GLOB_EVENDISCONN" : "Bontott kapcsolat esetén is",
	"SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "This option automatically connects to a server when a saved file is opened from the server or a saved file is within the current project and this project was created by this ftp extension. Oh, I really hope I explained it well...",
	"SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Jelenlegi projekt útvonal beszúrása",
	"SETTINGSWIND_GLOB_USELIST" : "Alternative folder retrieving",                                     // I can't translate right now
	"SETTINGSWIND_GLOB_KEEPALIVE" : "Keep alive", // Keep Alive is feature when client sends empty packages to server to prevet disconnection.
	"SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Az érték másodpercben. Ajánlott érték: 10. 0 esetén kikapcsolva.",
	"SETTINGSWIND_GLOB_DEBUG" : "Debug:",
	"SETTINGSWIND_GLOB_TIMEFORMAT" : "Dátum formátum:",
	"SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
	"SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Európai",
	"SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Ázsiai",
	"SETTINGSWIND_GLOB_SYNC" : "Szinkronizálás",
	"SETTINGSWIND_GLOB_SYNC_DESC" : "Törli vagy átnevezi a fájlt a távoli gépen ha módosult a programban.",
	"SETTINGSWIND_GLOB_AUTOCLEAR" : "Várólista automatikus ürítése-Auto-clear Queue",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Értesítések",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Időeltérés:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Ezzel a beállítással korrigálni tudod a 'Modosítva' oszlop tartalmát",

	"QUEUE_TITLE" : "eqFTP városor",
	"QUEUE_TITLE_HOVER" : "Kattints a városor megnyitásához",
	"QUEUE_HEADER_NAME" : "Név",
	"QUEUE_HEADER_PATH" : "Útvonal",
	"QUEUE_HEADER_FROM" : "Forrás",
	"QUEUE_HEADER_TO" : "Cél",
	"QUEUE_HEADER_STATUS" : "Állapot",
	"QUEUE_REMOVE" : "Törlés a várólistából",
	"QUEUE_CONTEXTM_STARTQ" : "Feladat indítása",
	"QUEUE_CONTEXTM_PAUSEQ" : "Feladat szüneteltetése",
	"QUEUE_CONTEXTM_CLEARQ" : "Városor ürítése",
	"QUEUE_CONTEXTM_CLEARCOMPQ" : "Elkészült feladatok ürítése",
	"QUEUE_CONTEXTM_CLEARFAILQ" : "Sikertelen feladatok ürítése",
	"QUEUE_CONTEXTM_CLEARPAUSQ" : "Szüneteltetett feladatok ürítése",
	"QUEUE_CONTEXTM_RESTARTFAILQ" : "Sikertelen feladatok újrapróbálása",
	"QUEUE_DONT_ADD_COMPLETED" : "Elkészült feladatok automatikus ürítése",
	"ERR_FILE_ACCESSDENIED" : "Hozzáférés megtagadva. Ellenőrizd a fájl/könyvtár jogosultságait.",
	"ERR_FILE_AUTHORIZATION" : "Sikertelen hitelesítés. Ellenőrizd a felhasználóneved/jelszavad.",
	"ERR_FILE_SERVNOEXIST" : "Szerver nem létezik. Talán elgépelted.",
	"ERR_FILE_SERVCANTREACH" : "Nem tudom elérni a szervert. Tipp: Ellenőrízd a tűzfalbeállításokat.",
	"ERR_FILE_FILESIZE0" : "Nem tudom letölteni a fájlt. A fájl mérete: 0B.",
    "ERR_FILE_DOWNLOAD" : "Nem tudom letölteni a fájlt.",
    "ERR_FILE_DOESNTEXIST" : "Fájl nem létezik.",
    "ERR_FOLDER_OPEN" : "Hiba történt a könytár projektként való megnyitásakor.",

	"CONTEXTM_DOWNLOAD" : "Letöltés",
	"CONTEXTM_UPLOAD" : "Feltöltés",
	"CONTEXTM_ADDQUEUE" : "Hozzáadás a városorhoz",
	"CONTEXTM_OPEN" : "Megnyitás",
	"CONTEXTM_DELETE" : "Törlés",
	"CONTEXTM_RENAME" : "Átnevezés",
	"CONTEXTM_REDOWNLOAD" : "Letöltés a szerverről",

	"OTHER_SELECT_SERVER_DROPDOWN" : "Válaszd ki a távoli szervert a kapcsolódáshoz...",
	"OTHER_ERROR" : "Hiba!",
	"OTHER_PAUSED" : "Szüneteltetve",
	"OTHER_COMPLETED" : "Elkészült",
	"OTHER_CANCELLED" : "Megszakítva",
	"OTHER_WAITING" : "Várakozik...",
	"OTHER_OK" : "Ok",
	"OTHER_CANCEL" : "Mégsem",
	"OTHER_APPLY" : "Alkalmaz",
	"OTHER_CLOSE" : "Bezárás",
	"OTHER_DELETE" : "Törlés",
	"OTHER_CONFIRM_DELETE" : "Biztosan törölni szeretnéd?",
	"OTHER_ERROR_EVENDISCONN" : "Nem tudom feltölteni a fájlt. A 'Bontott kapcsolat esetén is' beállítás ki van kapcsolva.",
});