define({
    "ERR_LOADING" : "Falha ao carregar :(",

    "SIDEPANEL_TITLE" : "eqFTP",
    "SIDEPANEL_OPENCONNMANGR" : "Abrir Gerenciador de Conexões",
    "SIDEPANEL_FILETREE_NAME" : "Nome",
    "SIDEPANEL_FILETREE_SIZE" : "Tamanho",
    "SIDEPANEL_FILETREE_TYPE" : "Tipo",
    "SIDEPANEL_FILETREE_MODIFIED" : "Modificado",
    "SIDEPANEL_CONDISCONNECT" : "(Des)conectar",
    "SIDEPANEL_REFRESH" : "Atualizar",
    "SIDEPANEL_RELOADSETTINGS" : "Recarregar configurações & Reentrar senha",

    "ERR_DIAG_SERVNOEXIST_TITLE" : "Servidor não existe",
    "ERR_DIAG_SERVNOEXIST_CONTENT" : "Parece que esse servidor não existe.<br>Verifique o servidor nas configurações da conexão.",
    "ERR_DIAG_SERVCANTREACH_TITLE" : "Servidor inalcançável",
    "ERR_DIAG_SERVCANTREACH_CONTENT" : "Não pude alcançar o servidor.<br>Talvez o seu firewall não me permita.",
    "ERR_DIAG_AUTHORIZEERR_TITLE" : "Dados de autorização incorretos",
    "ERR_DIAG_AUTHORIZEERR_CONTENT" : "Não consegui autorização com esse usuário e senha.<br>Por favor, verifique-os.",
    "ERR_DIAG_NOSERVERFOUND_TITLE" : "Não pude encontrar a conexão",
    "ERR_DIAG_NOSERVERFOUND_CONTENT" : "Não há nenhuma conexão eqFTP ligada ao projeto atual, e não há nenhum servidor conectado.<br>Conecte-se a um servidor, ou especifique a pasta do projeto atual como caminho local para a conexão em Configurações.",
    "ERR_DIAG_ECONNRESET_TITLE" : "O servidor está negando as conexões",
    "ERR_DIAG_ECONNRESET_CONTENT" : "Não pude conectar ao servidor, pois ele não me permite.<br>Experimente reiniciar o Brackets.",
    "ERR_DIAG_ECONNABORTED_TITLE" : "Você foi desconectado do servidor",
    "ERR_DIAG_ECONNABORTED_CONTENT" : "Conexão caiu. Tentando reconectar...",
    "ERR_DIAG_UNIVERSAL_TITLE" : "Houve um erro",
    "ERR_DIAG_UNIVERSAL_CONTENT" : "Veja esse erro! Como isso pôde acontecer?",

    "NOT_DIAG_CONNECTED" : "Conectado no servidor.",
    "NOT_DIAG_DISCONNECTED" : "Desconectado do servidor.",
    "NOT_DIAG_FILESDIFFERENT" : "Existem diferenças entre arquivos locais e remotos. Clique aqui para mais ações.",

    "PASSWDWIND_TITLE" : "Por favor, entre com sua senha",
    "PASSWDWIND_CONTENT" : "Sua senha para o eqFTP:",

    "CHECKDIFF_TITLE" : "Existem diferenças entre os arquivos",
    "CHECKDIFF_CONTENT" : "As versões local e remota do arquivo são diferentes. Por favor escolha uma ação.",
    "CHECKDIFF_BUTTON_COMPARE" : "Comparar arquivos",
    "CHECKDIFF_BUTTON_SHOWCHANGES" : "Mostrar alterações",
    "CHECKDIFF_BUTTON_KEEPLOCAL" : "Manter local", 
    "CHECKDIFF_BUTTON_KEEPLOCALALL" : "Manter versões locais da fila atual",
    "CHECKDIFF_BUTTON_GETREMOTE" : "Baixar remoto",
    "CHECKDIFF_BUTTON_GETREMOTEALL" : "Criar versões remotas da fila atual",

    "SETTINGSWIND_TITLE" : "Gerenciador de Conexões do eqFTP",
    "SETTINGSWIND_ERR_BLANKS" : "Nossa! Parece que aconteceu alguma coisa errada. Verifique os campos de entrada e tente novamente.",
    "SETTINGSWIND_ERR_CANTWRITE" : "Alguma coisa muito errada aconteceu! Não pude gravar as configurações no arquivo!",
    "SETTINGSWIND_ERR_LOCALPATHREPEAT" : "O caminho que você está tentando inserir está sendo usado por outra conexão.",
    "SETTINGSWIND_NOTIF_DONE" : "Tudo foi gravado! :)",
    "SETTINGSWIND_SAVEDCONN" : "Conexões FTP gravadas",
    "SETTINGSWIND_DELETECONN_HOVER" : "Remover esta conexão",
    "SETTINGSWIND_ERROR_DELETE_CURCONNSERV" : "Você não pode apagar a conexão que está usando",
    "SETTINGSWIND_ADDCONN_HOVER" : "Adicionar nova conexão",
    "SETTINGSWIND_ADDCONN_STRING" : "Criar nova conexão...",
    "SETTINGSWIND_DELETECONNCONF_1" : "Por favor, confirme a remoção da conexão ",
    "SETTINGSWIND_DELETECONNCONF_2" : ".",
    "SETTINGSWIND_OPENGLOBSET" : "Abrir configuração globais de FTP...",
    "SETTINGSWIND_NOTHINGYETMSG" : "Escolha a conexão para editar na barra lateral ou crie uma nova.",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ" : "Pasta para projetos:",
    "SETTINGSWIND_GLOB_FOLDERFORPROJ_DIAGTITLE" : "Diretório para projetos com arquivos baixados:",
    "SETTINGSWIND_GLOB_FOLDERFORSET" : "Pasta para configurações:",
    "SETTINGSWIND_GLOB_FOLDERFORSET_DIAGTITLE" : "Diretório para arquivo de configurações",
    "SETTINGSWIND_GLOB_DONTOPENPROJECTS" : "Não abrir projetos após download",
    "SETTINGSWIND_GLOB_MASTERPASSWORD" : "Senha Mestra",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_TITLE" : "Nome da conexão:",
    "SETTINGSWIND_GLOB_CONNECTIONNAME_FIELD" : "Digite o nome da conexão",
    "SETTINGSWIND_GLOB_SERVER_TITLE" : "Servidor:",
    "SETTINGSWIND_GLOB_PROTOCOL_TITLE" : "Tipo do protocolo:",
    "SETTINGSWIND_GLOB_USERNAME_TITLE" : "Usuário:",
    "SETTINGSWIND_GLOB_USERNAME_FIELD" : "Usuário do FTP",
    "SETTINGSWIND_GLOB_PASSWORD_TITLE" : "Senha:",
    "SETTINGSWIND_GLOB_PASSWORD_FIELD" : "Senha do FTP",
    "SETTINGSWIND_GLOB_RSA_TITLE" : "Chave RSA",
    "SETTINGSWIND_GLOB_RSA_FIELD" : "Clique para selecionar a chave RSA",
    "SETTINGSWIND_GLOB_FOLDERFORRSA_DIAGTITLE" : "Escolha o a caminho para a chave RSA",
    "SETTINGSWIND_GLOB_REMOTEPATH_TITLE" : "Caminho remoto:",
    "SETTINGSWIND_GLOB_REMOTEPATH_FIELD" : "Digite o caminho remoto para a pasta raiz do projeto",
    "SETTINGSWIND_GLOB_LOCALPATH_TITLE" : "Caminho local:",
    "SETTINGSWIND_GLOB_LOCALPATH_FIELD" : "Deixe em branco para criar uma nova pasta no local padrão",
    "SETTINGSWIND_GLOB_UPLOADONSAVE" : "Fazer upload do arquivo ao gravar",
    "SETTINGSWIND_GLOB_UPLOADONSAVEPAUSED" : "Adicionar para a fila pausada.",
    "SETTINGSWIND_GLOB_EVENDISCONN" : "Mesmo se desconectado",
    "SETTINGSWIND_GLOB_EVENDISCONN_EXPLAIN" : "Essa opção permite conectar automaticamente ao servidor quando o arquivo sendo gravado tiver sido aberto daquele servidor, ou quando o arquivo sendo gravado estiver dentro do projeto atual e este projeto tiver sido criado por esta extensão ftp. Nossa, espero ter conseguido explicar isso direito...",
    "SETTINGSWIND_GLOB_LOCALPATH_FILLWPROJECT_TITLE" : "Insira o caminho do projeto atual",
    "SETTINGSWIND_GLOB_USELIST" : "Usar método alternativo para listagem das pastas",
    "SETTINGSWIND_GLOB_KEEPALIVE" : "Intervalo de Keep Alive:",
    "SETTINGSWIND_GLOB_KEEPALIVE_DESC" : "Valor em segundos. O valor recomendado é 10. Use zero para desativar o keep alive e desconectar do servidor a cada comando executado.",
    "SETTINGSWIND_GLOB_DEBUG" : "Debug:",
    "SETTINGSWIND_GLOB_TIMEFORMAT" : "Formato da data:",
    "SETTINGSWIND_GLOB_TIMEFORMAT_US" : "US",
    "SETTINGSWIND_GLOB_TIMEFORMAT_EU" : "Europeu",
    "SETTINGSWIND_GLOB_TIMEFORMAT_ASIAN" : "Asiático",
    "SETTINGSWIND_GLOB_AUTOCLEAR" : "Fila auto-limpante",
    "SETTINGSWIND_GLOB_NOTIFICATIONS" : "Notificações",
    "SETTINGSWIND_GLOB_TIMEOFFSET" : "Intervalo de Tempo:",
    "SETTINGSWIND_GLOB_TIMEOFFSET_DESC" : "Use esta opção para acertar a hora da coluna Modificado",
    "SETTINGSWIND_GLOB_CONNECTIONTAB" : "Conexão",
    "SETTINGSWIND_GLOB_AUTOMATIZATIONTAB" : "Automatização",
    "SETTINGSWIND_GLOB_ADVANCEDTAB" : "Avançado",
    "SETTINGSWIND_GLOB_AUTO_SET_TITLE" : "Definir automatização:",
    "SETTINGSWIND_GLOB_AUTO_SYNC" : "Sincronizar", 
    "SETTINGSWIND_GLOB_AUTO_CLASSIC" : "Clássico",
    "SETTINGSWIND_GLOB_AUTO_SYNC_SELECT_TITLE" : "Selecionar o que sincronizar",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILECREATION" : "Criação de arquivo",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FOLDERCREATION" : "Criação de pasta",
    "SETTINGSWIND_GLOB_AUTO_SYNC_FILEUPLOAD" : "Atualização de arquivo",
    "SETTINGSWIND_GLOB_AUTO_SYNC_RENAMING" : "Renomeando",
    "SETTINGSWIND_GLOB_AUTO_SYNC_MOVING" : "Movendo",
    "SETTINGSWIND_GLOB_AUTO_SYNC_DELETING" : "Apagando",
    "SETTINGSWIND_GLOB_AUTO_SYNC_EXTRASETTINGS_TITLE" : "Configurações extra",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF" : "Verificar differenças",
    "SETTINGSWIND_GLOB_AUTO_SYNC_CHECKDIFF_EXPLAIN" : "Quando abrir arquivo local ou remoto",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_TITLE" : "Lista ignorada",
    "SETTINGSWIND_GLOB_AUTO_SYNC_IGNORELIST_EXPLAIN" : "Mesma sintaxe do .gitignore",
    "SETTINGSWIND_GLOB_SYNCLOCPROJWCONN" : "Abre projeto Local relacionado depois de mudar a conexão e vice-versa",
    "SETTINGS_NOTIF_RELOADED" : "Configurações recarregadas com sucesso.",
    "SETTINGS_ERROR_RELOADED" : "Não foi possível recarregar as configurações.",

    "QUEUE_TITLE" : "Fila eqFTP",
    "QUEUE_HEADER_NAME" : "Nome",
    "QUEUE_HEADER_PATH" : "Caminho",
    "QUEUE_HEADER_FROM" : "De/Origem",
    "QUEUE_HEADER_TO" : "Para/Destino",
    "QUEUE_HEADER_STATUS" : "Status",
    "QUEUE_CLEARQ" : "Limpar fila",
    "QUEUE_STARTQ" : "Fila para Iniciar",
    "QUEUE_PAUSEQ" : "Fila em Pausa",
    "QUEUE_RESTARTQ" : "Reinicio Falhou",
    "QUEUE_CONTEXTM_STARTT" : "Iniciar",
    "QUEUE_CONTEXTM_PAUSET" : "Pausas",
    "QUEUE_CONTEXTM_REMOVET" : "Remover",
    "QUEUE_CONTEXTM_RESTARTT" : "Reiniciar",
    "QUEUE_TASK_STATUS_WAITING" : "Esperando",
    "QUEUE_TASK_STATUS_SUCCESS" : "Encerrado",
    "QUEUE_TASK_STATUS_FAIL" : "Falhou",
    "QUEUE_TASK_STATUS_PAUSE" : "Pausado",
    "QUEUE_TASK_STATUS_STARTED" : "Iniciado",
    "QUEUE_TASK_STATUS_DELETED" : "Removido",
    "QUEUE_DONT_ADD_COMPLETED" : "Auto-limpeza terminou suas tarefas",
    
    "ERR_FILE_ACCESSDENIED" : "Acesso negado. Verifique as permissões do arquivo.",
    "ERR_FILE_AUTHORIZATION" : "Erro de autorização. Verifique seu usuário e senha.",
    "ERR_FILE_SERVNOEXIST" : "Servidor não existe. Talvez você tenha digitado errado o endereço.",
    "ERR_FILE_SERVCANTREACH" : "Não pude alcançar o servidor. Verifique o firewall.",
    "ERR_FILE_FILESIZE0" : "Não consigo baixar o arquivo. Tamanho 0.",
    "ERR_FILE_DOWNLOAD" : "Não consigo baixar o arquivo.",
    "ERR_FILE_UPLOAD" : "Não consgo enviar o arquivo.",
    "ERR_FILE_DOESNTEXIST" : "Arquivo não existe",
    "ERR_FILE_CANTRENAME" : "Não consigo renomear o arquivo: ",
    "ERR_FILE_CANTDELETE" : "Não consigo remover o arquivo: ",
    "ERR_FILE_CANTCREATEDIR" : "Não consigo criar a pasta: ",
    "ERR_FILE_CANTDELETEDIR" : "Não consigo remover a pasta: ",
    "ERR_FILE_CANTCREATEFILE" : "Não consigo criar o arquivo: ",
    "ERR_FOLDER_OPEN" : "Occoreu um erro ao abrir a pasta como um projeto",

    "CONTEXTM_DOWNLOAD" : "Download",
    "CONTEXTM_UPLOAD" : "Upload",
    "CONTEXTM_ADDQUEUE" : "Adicionar à Fila",
    "CONTEXTM_OPEN" : "Abrir",
    "CONTEXTM_DELETE" : "Excluir",
    "CONTEXTM_RENAME" : "Renomear",
    "CONTEXTM_REDOWNLOAD" : "Baixar do servidor",
    "CONTEXTM_CREATEFILE" : "Criar arquivo",
    "CONTEXTM_CREATEFOLDER" : "Criar pasta",

    "OTHER_SELECT_SERVER_DROPDOWN" : "Selecionar servidor remoto para conexão...",
    "OTHER_ERROR" : "Erro",
    "OTHER_PAUSED" : "Pausado",
    "OTHER_COMPLETED" : "Completo",
    "OTHER_CANCELLED" : "Cancelado",
    "OTHER_WAITING" : "Aguardando",
    "OTHER_OK" : "Ok",
    "OTHER_OFF" : "Desligar",
    "OTHER_CANCEL" : "Cancelar",
    "OTHER_APPLY" : "Aplicar",
    "OTHER_SAVE" : "Gravar",
    "OTHER_CLOSE" : "Fechar",
    "OTHER_DELETE" : "Excluir",
    "OTHER_CONFIRM_DELETE" : "Tem certeza que quer remover este item?",
    "OTHER_CONFIRM_SETTINGSCLOSE" : "Existem mudanças não gravadas que serão perdidas se você clicar em OK.<br>Quer continuar?",
    "OTHER_ERROR_EVENDISCONN" : "Não consigo enviar o arquivo. A opção 'Mesmo se desconectado' está desativada.",
    "OTHER_ERROR_CANTREADSETTINGS" : "Não consigo ler as preferências. Provavelmente digitou uma senha mestra errada."
});